<?php

/*
 * SPDX-License-Identifier: Apache-2.0
 * Derived from the official Zenlayer Cloud SDK schema and modified for
 * PHP/Laravel. See NOTICE and UPSTREAM.md for attribution and revisions.
 */

declare(strict_types=1);

namespace ZenlayerCloud\Laravel\Zec\V20250901;

use ZenlayerCloud\Laravel\Common\AbstractClient;

/**
 * Zenlayer Cloud Elastic Compute (ZEC) client (API version 2025-09-01).
 *
 * Each public method maps 1:1 to an official Action name. The public API
 * reference is at https://docs.console.zenlayer.com/api-reference/compute/zec;
 * UPSTREAM.md records any Action currently present only in the official SDKs.
 * Method names remain PascalCase so the protocol mapping is unambiguous.
 *
 * @generated by bin/codegen.php — do not edit by hand.
 */
class ZecClient extends AbstractClient
{
    protected function service(): string
    {
        return 'zec';
    }

    protected function apiVersion(): string
    {
        return '2025-09-01';
    }

    /**
     * 查询可用区信息。包括名称，所属的节点等。
     */
    public function DescribeZones(#[\SensitiveParameter] Models\DescribeZonesRequest $request): Models\DescribeZonesResponse
    {
        return $this->call('DescribeZones', $request, Models\DescribeZonesResponse::class);
    }

    /**
     * 查询节点信息。包括名称、所属的行政区划等。
     */
    public function DescribeRegions(#[\SensitiveParameter] Models\DescribeRegionsRequest $request): Models\DescribeRegionsResponse
    {
        return $this->call('DescribeRegions', $request, Models\DescribeRegionsResponse::class);
    }

    /**
     * 查询可用区售卖的机型信息。
     */
    public function DescribeZoneInstanceConfigInfos(#[\SensitiveParameter] Models\DescribeZoneInstanceConfigInfosRequest $request): Models\DescribeZoneInstanceConfigInfosResponse
    {
        return $this->call('DescribeZoneInstanceConfigInfos', $request, Models\DescribeZoneInstanceConfigInfosResponse::class);
    }

    /**
     * 查询各节点VM库存容量级别信息。
     */
    public function DescribeVmInventoryCapacity(#[\SensitiveParameter] Models\DescribeVmInventoryCapacityRequest $request): Models\DescribeVmInventoryCapacityResponse
    {
        return $this->call('DescribeVmInventoryCapacity', $request, Models\DescribeVmInventoryCapacityResponse::class);
    }

    /**
     * 查询时区信息。
     */
    public function DescribeTimeZones(#[\SensitiveParameter] Models\DescribeTimeZonesRequest $request): Models\DescribeTimeZonesResponse
    {
        return $this->call('DescribeTimeZones', $request, Models\DescribeTimeZonesResponse::class);
    }

    /**
     * 创建虚拟机实例询价。
     */
    public function InquiryPriceCreateInstance(#[\SensitiveParameter] Models\InquiryPriceCreateInstanceRequest $request): Models\InquiryPriceCreateInstanceResponse
    {
        return $this->call('InquiryPriceCreateInstance', $request, Models\InquiryPriceCreateInstanceResponse::class);
    }

    /**
     * 创建一台或多台虚拟机实例。
     */
    public function CreateZecInstances(#[\SensitiveParameter] Models\CreateZecInstancesRequest $request): Models\CreateZecInstancesResponse
    {
        return $this->call('CreateZecInstances', $request, Models\CreateZecInstancesResponse::class);
    }

    /**
     * 查询一台或多台虚拟机实例的信息。用户可以根据实例ID、实例名称等条件来查询实例的详细信息。
     */
    public function DescribeInstances(#[\SensitiveParameter] Models\DescribeInstancesRequest $request): Models\DescribeInstancesResponse
    {
        return $this->call('DescribeInstances', $request, Models\DescribeInstancesResponse::class);
    }

    /**
     * 批量查询一个或多个弹性计算实例的当前运行状态，支持按实例 ID 列表和资源组筛选，支持分页查询。
     */
    public function DescribeInstancesStatus(#[\SensitiveParameter] Models\DescribeInstancesStatusRequest $request): Models\DescribeInstancesStatusResponse
    {
        return $this->call('DescribeInstancesStatus', $request, Models\DescribeInstancesStatusResponse::class);
    }

    /**
     * 修改实例属性（名称）。
     */
    public function ModifyInstancesAttribute(#[\SensitiveParameter] Models\ModifyInstancesAttributeRequest $request): Models\ModifyInstancesAttributeResponse
    {
        return $this->call('ModifyInstancesAttribute', $request, Models\ModifyInstancesAttributeResponse::class);
    }

    /**
     * 启动一台或多台虚拟机实例。
     */
    public function StartInstances(#[\SensitiveParameter] Models\StartInstancesRequest $request): Models\StartInstancesResponse
    {
        return $this->call('StartInstances', $request, Models\StartInstancesResponse::class);
    }

    /**
     * 关闭一台或多台虚拟机实例。
     */
    public function StopInstances(#[\SensitiveParameter] Models\StopInstancesRequest $request): Models\StopInstancesResponse
    {
        return $this->call('StopInstances', $request, Models\StopInstancesResponse::class);
    }

    /**
     * 重启虚拟机实例。
     */
    public function RebootInstances(#[\SensitiveParameter] Models\RebootInstancesRequest $request): Models\RebootInstancesResponse
    {
        return $this->call('RebootInstances', $request, Models\RebootInstancesResponse::class);
    }

    /**
     * 重置一台虚拟机实例密码。
     */
    public function ResetInstancePassword(#[\SensitiveParameter] Models\ResetInstancePasswordRequest $request): Models\ResetInstancePasswordResponse
    {
        return $this->call('ResetInstancePassword', $request, Models\ResetInstancePasswordResponse::class);
    }

    /**
     * 重装一台虚拟机实例操作系统。
     */
    public function ResetInstance(#[\SensitiveParameter] Models\ResetInstanceRequest $request): Models\ResetInstanceResponse
    {
        return $this->call('ResetInstance', $request, Models\ResetInstanceResponse::class);
    }

    /**
     * 对一批弹性计算实例执行操作系统重装，可重新指定镜像、登录方式（密码或密钥对）、时区及实例名称。
     */
    public function ResetInstances(#[\SensitiveParameter] Models\ResetInstancesRequest $request): Models\ResetInstancesResponse
    {
        return $this->call('ResetInstances', $request, Models\ResetInstancesResponse::class);
    }

    /**
     * 为指定弹性计算实例开启 IP 转发，开启后该实例可作为路由器或网关转发来自其他资源的网络流量。
     */
    public function StartIpForward(#[\SensitiveParameter] Models\StartIpForwardRequest $request): Models\StartIpForwardResponse
    {
        return $this->call('StartIpForward', $request, Models\StartIpForwardResponse::class);
    }

    /**
     * 为指定弹性计算实例关闭 IP 转发功能，关闭后该实例将不再转发非本机目的地的网络流量。
     */
    public function StopIpForward(#[\SensitiveParameter] Models\StopIpForwardRequest $request): Models\StopIpForwardResponse
    {
        return $this->call('StopIpForward', $request, Models\StopIpForwardResponse::class);
    }

    /**
     * 为指定弹性计算实例开启 QEMU Guest Agent（QGA）监控数据采集，开启后可通过监控接口获取实例内部性能指标数据。
     */
    public function StartAgentMonitor(#[\SensitiveParameter] Models\StartAgentMonitorRequest $request): Models\StartAgentMonitorResponse
    {
        return $this->call('StartAgentMonitor', $request, Models\StartAgentMonitorResponse::class);
    }

    /**
     * 为指定弹性计算实例关闭 QEMU Guest Agent（QGA）监控数据采集功能，关闭后将无法通过监控接口获取实例内部性能数据。
     */
    public function StopAgentMonitor(#[\SensitiveParameter] Models\StopAgentMonitorRequest $request): Models\StopAgentMonitorResponse
    {
        return $this->call('StopAgentMonitor', $request, Models\StopAgentMonitorResponse::class);
    }

    /**
     * 将指定弹性计算实例的规格变更为目标规格。
     */
    public function ModifyInstanceType(#[\SensitiveParameter] Models\ModifyInstanceTypeRequest $request): Models\ModifyInstanceTypeResponse
    {
        return $this->call('ModifyInstanceType', $request, Models\ModifyInstanceTypeResponse::class);
    }

    /**
     * 更改实例的网卡模式。
     */
    public function ChangeNicNetworkType(#[\SensitiveParameter] Models\ChangeNicNetworkTypeRequest $request): Models\ChangeNicNetworkTypeResponse
    {
        return $this->call('ChangeNicNetworkType', $request, Models\ChangeNicNetworkTypeResponse::class);
    }

    /**
     * 销毁一台或多台虚拟机实例。
     */
    public function ReleaseInstances(#[\SensitiveParameter] Models\ReleaseInstancesRequest $request): Models\ReleaseInstancesResponse
    {
        return $this->call('ReleaseInstances', $request, Models\ReleaseInstancesResponse::class);
    }

    /**
     * 获取实例VNC地址。
     */
    public function DescribeVncUrl(#[\SensitiveParameter] Models\DescribeVncUrlRequest $request): Models\DescribeVncUrlResponse
    {
        return $this->call('DescribeVncUrl', $request, Models\DescribeVncUrlResponse::class);
    }

    /**
     * 查询一段时间的实例的监控指标数据。包括CPU,内存等相关指标数据。
     */
    public function DescribeInstanceMonitorData(#[\SensitiveParameter] Models\DescribeInstanceMonitorDataRequest $request): Models\DescribeInstanceMonitorDataResponse
    {
        return $this->call('DescribeInstanceMonitorData', $request, Models\DescribeInstanceMonitorDataResponse::class);
    }

    /**
     * 查询变更实例规格后的价格，同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceModifyInstanceType(#[\SensitiveParameter] Models\InquiryPriceModifyInstanceTypeRequest $request): Models\InquiryPriceModifyInstanceTypeResponse
    {
        return $this->call('InquiryPriceModifyInstanceType', $request, Models\InquiryPriceModifyInstanceTypeResponse::class);
    }

    /**
     * 查询可用区售卖的 GPU 规格信息。
     */
    public function DescribeZoneGpuInstanceConfigInfos(#[\SensitiveParameter] Models\DescribeZoneGpuInstanceConfigInfosRequest $request): Models\DescribeZoneGpuInstanceConfigInfosResponse
    {
        return $this->call('DescribeZoneGpuInstanceConfigInfos', $request, Models\DescribeZoneGpuInstanceConfigInfosResponse::class);
    }

    /**
     * 查询可用区售卖的加速卡规格信息。
     */
    public function DescribeZoneAcceleratorConfigInfos(#[\SensitiveParameter] Models\DescribeZoneAcceleratorConfigInfosRequest $request): Models\DescribeZoneAcceleratorConfigInfosResponse
    {
        return $this->call('DescribeZoneAcceleratorConfigInfos', $request, Models\DescribeZoneAcceleratorConfigInfosResponse::class);
    }

    /**
     * 查询某节点支持的镜像列表。
     */
    public function DescribeImages(#[\SensitiveParameter] Models\DescribeImagesRequest $request): Models\DescribeImagesResponse
    {
        return $this->call('DescribeImages', $request, Models\DescribeImagesResponse::class);
    }

    /**
     * 用实例创建自定义镜像。
     */
    public function CreateImage(#[\SensitiveParameter] Models\CreateImageRequest $request): Models\CreateImageResponse
    {
        return $this->call('CreateImage', $request, Models\CreateImageResponse::class);
    }

    /**
     * 查询当前账号下的自定义镜像列表。
     */
    public function DescribeCustomImages(#[\SensitiveParameter] Models\DescribeCustomImagesRequest $request): Models\DescribeCustomImagesResponse
    {
        return $this->call('DescribeCustomImages', $request, Models\DescribeCustomImagesResponse::class);
    }

    /**
     * 修改自定义镜像属性。
     */
    public function ModifyImagesAttributes(#[\SensitiveParameter] Models\ModifyImagesAttributesRequest $request): Models\ModifyImagesAttributesResponse
    {
        return $this->call('ModifyImagesAttributes', $request, Models\ModifyImagesAttributesResponse::class);
    }

    /**
     * 删除一个或多个镜像。
     */
    public function DeleteImages(#[\SensitiveParameter] Models\DeleteImagesRequest $request): Models\DeleteImagesResponse
    {
        return $this->call('DeleteImages', $request, Models\DeleteImagesResponse::class);
    }

    /**
     * 将自定义镜像复制到指定区域列表。
     */
    public function CopyImage(#[\SensitiveParameter] Models\CopyImageRequest $request): Models\CopyImageResponse
    {
        return $this->call('CopyImage', $request, Models\CopyImageResponse::class);
    }

    /**
     * 删除镜像在指定区域的副本。
     */
    public function DeleteImageCopy(#[\SensitiveParameter] Models\DeleteImageCopyRequest $request): Models\DeleteImageCopyResponse
    {
        return $this->call('DeleteImageCopy', $request, Models\DeleteImageCopyResponse::class);
    }

    /**
     * 查询自定义镜像在各个目标区域的复制进度。
     */
    public function DescribeImageCopyProgress(#[\SensitiveParameter] Models\DescribeImageCopyProgressRequest $request): Models\DescribeImageCopyProgressResponse
    {
        return $this->call('DescribeImageCopyProgress', $request, Models\DescribeImageCopyProgressResponse::class);
    }

    /**
     * 查询支持售卖云硬盘的节点信息。
     */
    public function DescribeDiskRegions(#[\SensitiveParameter] Models\DescribeDiskRegionsRequest $request): Models\DescribeDiskRegionsResponse
    {
        return $this->call('DescribeDiskRegions', $request, Models\DescribeDiskRegionsResponse::class);
    }

    /**
     * 查询可用区支持的云盘类型。
     */
    public function DescribeDiskCategory(#[\SensitiveParameter] Models\DescribeDiskCategoryRequest $request): Models\DescribeDiskCategoryResponse
    {
        return $this->call('DescribeDiskCategory', $request, Models\DescribeDiskCategoryResponse::class);
    }

    /**
     * 创建一块或多块云硬盘的询价。
     */
    public function InquiryPriceCreateDisks(#[\SensitiveParameter] Models\InquiryPriceCreateDisksRequest $request): Models\InquiryPriceCreateDisksResponse
    {
        return $this->call('InquiryPriceCreateDisks', $request, Models\InquiryPriceCreateDisksResponse::class);
    }

    /**
     * 查询云盘的列表信息。
     */
    public function DescribeDisks(#[\SensitiveParameter] Models\DescribeDisksRequest $request): Models\DescribeDisksResponse
    {
        return $this->call('DescribeDisks', $request, Models\DescribeDisksResponse::class);
    }

    /**
     * 创建一个或多个云硬盘。
     */
    public function CreateDisks(#[\SensitiveParameter] Models\CreateDisksRequest $request): Models\CreateDisksResponse
    {
        return $this->call('CreateDisks', $request, Models\CreateDisksResponse::class);
    }

    /**
     * 云硬盘挂载到实例上。
     */
    public function AttachDisks(#[\SensitiveParameter] Models\AttachDisksRequest $request): Models\AttachDisksResponse
    {
        return $this->call('AttachDisks', $request, Models\AttachDisksResponse::class);
    }

    /**
     * 将云硬盘从主机实例上卸载。
     */
    public function DetachDisks(#[\SensitiveParameter] Models\DetachDisksRequest $request): Models\DetachDisksResponse
    {
        return $this->call('DetachDisks', $request, Models\DetachDisksResponse::class);
    }

    /**
     * 修改一块或多块云硬盘属性。当前接口只支持修改名称。
     */
    public function ModifyDisksAttributes(#[\SensitiveParameter] Models\ModifyDisksAttributesRequest $request): Models\ModifyDisksAttributesResponse
    {
        return $this->call('ModifyDisksAttributes', $request, Models\ModifyDisksAttributesResponse::class);
    }

    /**
     * 将一个云硬盘扩容到指定大小。
     */
    public function ResizeDisk(#[\SensitiveParameter] Models\ResizeDiskRequest $request): Models\ResizeDiskResponse
    {
        return $this->call('ResizeDisk', $request, Models\ResizeDiskResponse::class);
    }

    /**
     * 删除释放一块云硬盘。
     */
    public function ReleaseDisk(#[\SensitiveParameter] Models\ReleaseDiskRequest $request): Models\ReleaseDiskResponse
    {
        return $this->call('ReleaseDisk', $request, Models\ReleaseDiskResponse::class);
    }

    /**
     * 恢复处于回收状态的云硬盘，使其重新可用。仅可恢复保留期内的已删除云硬盘，超出保留期后资源将被彻底销毁。
     */
    public function RenewDisk(#[\SensitiveParameter] Models\RenewDiskRequest $request): Models\RenewDiskResponse
    {
        return $this->call('RenewDisk', $request, Models\RenewDiskResponse::class);
    }

    /**
     * 修改云硬盘所属的资源组。
     */
    public function ModifyDisksResourceGroup(#[\SensitiveParameter] Models\ModifyDisksResourceGroupRequest $request): Models\ModifyDisksResourceGroupResponse
    {
        return $this->call('ModifyDisksResourceGroup', $request, Models\ModifyDisksResourceGroupResponse::class);
    }

    /**
     * 查询一段时间的云硬盘的监控指标数据。
     */
    public function DescribeDiskMonitorData(#[\SensitiveParameter] Models\DescribeDiskMonitorDataRequest $request): Models\DescribeDiskMonitorDataResponse
    {
        return $this->call('DescribeDiskMonitorData', $request, Models\DescribeDiskMonitorDataResponse::class);
    }

    /**
     * 查询云硬盘扩容后的新价格。同时通过 previousPrices 返回扩容前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceResizeDisk(#[\SensitiveParameter] Models\InquiryPriceResizeDiskRequest $request): Models\InquiryPriceResizeDiskResponse
    {
        return $this->call('InquiryPriceResizeDisk', $request, Models\InquiryPriceResizeDiskResponse::class);
    }

    /**
     * 查询快照的详细信息。
     */
    public function DescribeSnapshots(#[\SensitiveParameter] Models\DescribeSnapshotsRequest $request): Models\DescribeSnapshotsResponse
    {
        return $this->call('DescribeSnapshots', $request, Models\DescribeSnapshotsResponse::class);
    }

    /**
     * 对指定云盘创建快照。
     */
    public function CreateSnapshot(#[\SensitiveParameter] Models\CreateSnapshotRequest $request): Models\CreateSnapshotResponse
    {
        return $this->call('CreateSnapshot', $request, Models\CreateSnapshotResponse::class);
    }

    /**
     * 修改指定快照的属性。
     */
    public function ModifySnapshotsAttribute(#[\SensitiveParameter] Models\ModifySnapshotsAttributeRequest $request): Models\ModifySnapshotsAttributeResponse
    {
        return $this->call('ModifySnapshotsAttribute', $request, Models\ModifySnapshotsAttributeResponse::class);
    }

    /**
     * 回滚快照到原云盘。
     */
    public function ApplySnapshot(#[\SensitiveParameter] Models\ApplySnapshotRequest $request): Models\ApplySnapshotResponse
    {
        return $this->call('ApplySnapshot', $request, Models\ApplySnapshotResponse::class);
    }

    /**
     * 删除指定快照集合。
     */
    public function DeleteSnapshots(#[\SensitiveParameter] Models\DeleteSnapshotsRequest $request): Models\DeleteSnapshotsResponse
    {
        return $this->call('DeleteSnapshots', $request, Models\DeleteSnapshotsResponse::class);
    }

    /**
     * 创建一个自动快照策略。
     */
    public function CreateAutoSnapshotPolicy(#[\SensitiveParameter] Models\CreateAutoSnapshotPolicyRequest $request): Models\CreateAutoSnapshotPolicyResponse
    {
        return $this->call('CreateAutoSnapshotPolicy', $request, Models\CreateAutoSnapshotPolicyResponse::class);
    }

    /**
     * 查询自动快照策略的列表数据。
     */
    public function DescribeAutoSnapshotPolicies(#[\SensitiveParameter] Models\DescribeAutoSnapshotPoliciesRequest $request): Models\DescribeAutoSnapshotPoliciesResponse
    {
        return $this->call('DescribeAutoSnapshotPolicies', $request, Models\DescribeAutoSnapshotPoliciesResponse::class);
    }

    /**
     * 云硬盘添加到指定的自动快照策略。
     */
    public function ApplyAutoSnapshotPolicy(#[\SensitiveParameter] Models\ApplyAutoSnapshotPolicyRequest $request): Models\ApplyAutoSnapshotPolicyResponse
    {
        return $this->call('ApplyAutoSnapshotPolicy', $request, Models\ApplyAutoSnapshotPolicyResponse::class);
    }

    /**
     * 云硬盘从指定的自动快照策略中移除。
     */
    public function CancelAutoSnapshotPolicy(#[\SensitiveParameter] Models\CancelAutoSnapshotPolicyRequest $request): Models\CancelAutoSnapshotPolicyResponse
    {
        return $this->call('CancelAutoSnapshotPolicy', $request, Models\CancelAutoSnapshotPolicyResponse::class);
    }

    /**
     * 修改自动快照策略的基本信息。
     */
    public function ModifyAutoSnapshotPolicy(#[\SensitiveParameter] Models\ModifyAutoSnapshotPolicyRequest $request): Models\ModifyAutoSnapshotPolicyResponse
    {
        return $this->call('ModifyAutoSnapshotPolicy', $request, Models\ModifyAutoSnapshotPolicyResponse::class);
    }

    /**
     * 删除指定的自动快照策略。
     */
    public function DeleteAutoSnapshotPolicies(#[\SensitiveParameter] Models\DeleteAutoSnapshotPoliciesRequest $request): Models\DeleteAutoSnapshotPoliciesResponse
    {
        return $this->call('DeleteAutoSnapshotPolicies', $request, Models\DeleteAutoSnapshotPoliciesResponse::class);
    }

    /**
     * 支持售卖网卡的区域信息。
     */
    public function DescribeNetworkInterfaceRegions(#[\SensitiveParameter] Models\DescribeNetworkInterfaceRegionsRequest $request): Models\DescribeNetworkInterfaceRegionsResponse
    {
        return $this->call('DescribeNetworkInterfaceRegions', $request, Models\DescribeNetworkInterfaceRegionsResponse::class);
    }

    /**
     * 查询一个或多个指定网卡的信息。用户可以根据 网卡ID、网卡名称等信息来搜索网卡信息。
     */
    public function DescribeNetworkInterfaces(#[\SensitiveParameter] Models\DescribeNetworkInterfacesRequest $request): Models\DescribeNetworkInterfacesResponse
    {
        return $this->call('DescribeNetworkInterfaces', $request, Models\DescribeNetworkInterfacesResponse::class);
    }

    /**
     * 修改一张网卡的属性。
     */
    public function ModifyNetworkInterfaceAttribute(#[\SensitiveParameter] Models\ModifyNetworkInterfaceAttributeRequest $request): Models\ModifyNetworkInterfaceAttributeResponse
    {
        return $this->call('ModifyNetworkInterfaceAttribute', $request, Models\ModifyNetworkInterfaceAttributeResponse::class);
    }

    /**
     * 修改网卡的属性，目前只支持修改网卡的名称。
     */
    public function ModifyNetworkInterfacesAttribute(#[\SensitiveParameter] Models\ModifyNetworkInterfacesAttributeRequest $request): Models\ModifyNetworkInterfacesAttributeResponse
    {
        return $this->call('ModifyNetworkInterfacesAttribute', $request, Models\ModifyNetworkInterfacesAttributeResponse::class);
    }

    /**
     * 创建一张辅助网卡。
     */
    public function CreateNetworkInterface(#[\SensitiveParameter] Models\CreateNetworkInterfaceRequest $request): Models\CreateNetworkInterfaceResponse
    {
        return $this->call('CreateNetworkInterface', $request, Models\CreateNetworkInterfaceResponse::class);
    }

    /**
     * 删除一张辅助网卡。
     */
    public function DeleteNetworkInterface(#[\SensitiveParameter] Models\DeleteNetworkInterfaceRequest $request): Models\DeleteNetworkInterfaceResponse
    {
        return $this->call('DeleteNetworkInterface', $request, Models\DeleteNetworkInterfaceResponse::class);
    }

    /**
     * 网卡绑定实例。
     */
    public function AttachNetworkInterface(#[\SensitiveParameter] Models\AttachNetworkInterfaceRequest $request): Models\AttachNetworkInterfaceResponse
    {
        return $this->call('AttachNetworkInterface', $request, Models\AttachNetworkInterfaceResponse::class);
    }

    /**
     * 将一张网卡从实例上解绑。
     */
    public function DetachNetworkInterface(#[\SensitiveParameter] Models\DetachNetworkInterfaceRequest $request): Models\DetachNetworkInterfaceResponse
    {
        return $this->call('DetachNetworkInterface', $request, Models\DetachNetworkInterfaceResponse::class);
    }

    /**
     * 网卡绑定内网IPv4。
     */
    public function AssignNetworkInterfaceIpv4(#[\SensitiveParameter] Models\AssignNetworkInterfaceIpv4Request $request): Models\AssignNetworkInterfaceIpv4Response
    {
        return $this->call('AssignNetworkInterfaceIpv4', $request, Models\AssignNetworkInterfaceIpv4Response::class);
    }

    /**
     * 将一张网卡额外添加内网IPv4地址。
     */
    public function BatchAssignNetworkInterfaceIpv4(#[\SensitiveParameter] Models\BatchAssignNetworkInterfaceIpv4Request $request): Models\BatchAssignNetworkInterfaceIpv4Response
    {
        return $this->call('BatchAssignNetworkInterfaceIpv4', $request, Models\BatchAssignNetworkInterfaceIpv4Response::class);
    }

    /**
     * 将网卡上的内网IPv4地址解绑。
     */
    public function UnassignNetworkInterfaceIpv4(#[\SensitiveParameter] Models\UnassignNetworkInterfaceIpv4Request $request): Models\UnassignNetworkInterfaceIpv4Response
    {
        return $this->call('UnassignNetworkInterfaceIpv4', $request, Models\UnassignNetworkInterfaceIpv4Response::class);
    }

    /**
     * 查询指定弹性网卡（vNIC）上已分配的公网 IPv6 地址及其计费、带宽配置信息。
     */
    public function DescribeNetworkInterfacePublicIPv6(#[\SensitiveParameter] Models\DescribeNetworkInterfacePublicIPv6Request $request): Models\DescribeNetworkInterfacePublicIPv6Response
    {
        return $this->call('DescribeNetworkInterfacePublicIPv6', $request, Models\DescribeNetworkInterfacePublicIPv6Response::class);
    }

    /**
     * 公网Ipv6流量包或固定带宽询价。
     */
    public function InquiryPricePublicIpv6(#[\SensitiveParameter] Models\InquiryPricePublicIpv6Request $request): Models\InquiryPricePublicIpv6Response
    {
        return $this->call('InquiryPricePublicIpv6', $request, Models\InquiryPricePublicIpv6Response::class);
    }

    /**
     * 查询变更IPv6网络计费模式后的价格。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceChangeIpv6InternetChargeType(#[\SensitiveParameter] Models\InquiryPriceChangeIpv6InternetChargeTypeRequest $request): Models\InquiryPriceChangeIpv6InternetChargeTypeResponse
    {
        return $this->call('InquiryPriceChangeIpv6InternetChargeType', $request, Models\InquiryPriceChangeIpv6InternetChargeTypeResponse::class);
    }

    /**
     * 给网卡添加IPv6。
     */
    public function AssignNetworkInterfaceIpv6(#[\SensitiveParameter] Models\AssignNetworkInterfaceIpv6Request $request): Models\AssignNetworkInterfaceIpv6Response
    {
        return $this->call('AssignNetworkInterfaceIpv6', $request, Models\AssignNetworkInterfaceIpv6Response::class);
    }

    /**
     * 删除网卡IPv6。
     */
    public function UnassignNetworkInterfaceIpv6(#[\SensitiveParameter] Models\UnassignNetworkInterfaceIpv6Request $request): Models\UnassignNetworkInterfaceIpv6Response
    {
        return $this->call('UnassignNetworkInterfaceIpv6', $request, Models\UnassignNetworkInterfaceIpv6Response::class);
    }

    /**
     * 查询一段时间内的网卡监控指标数据。包含带宽、包量、丢包、错误包等指标。
     */
    public function DescribeNetworkInterfaceMonitorData(#[\SensitiveParameter] Models\DescribeNetworkInterfaceMonitorDataRequest $request): Models\DescribeNetworkInterfaceMonitorDataResponse
    {
        return $this->call('DescribeNetworkInterfaceMonitorData', $request, Models\DescribeNetworkInterfaceMonitorDataResponse::class);
    }

    /**
     * 修改指定公网IPv6的带宽限速模式。
     */
    public function ModifyNetworkInterfacePublicIPv6BandwidthLimitMode(#[\SensitiveParameter] Models\ModifyNetworkInterfacePublicIPv6BandwidthLimitModeRequest $request): Models\ModifyNetworkInterfacePublicIPv6BandwidthLimitModeResponse
    {
        return $this->call('ModifyNetworkInterfacePublicIPv6BandwidthLimitMode', $request, Models\ModifyNetworkInterfacePublicIPv6BandwidthLimitModeResponse::class);
    }

    /**
     * 查询调整IPv6带宽后的价格。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceModifyIpv6Bandwidth(#[\SensitiveParameter] Models\InquiryPriceModifyIpv6BandwidthRequest $request): Models\InquiryPriceModifyIpv6BandwidthResponse
    {
        return $this->call('InquiryPriceModifyIpv6Bandwidth', $request, Models\InquiryPriceModifyIpv6BandwidthResponse::class);
    }

    /**
     * 调整公网IPv6的带宽限速。
     */
    public function ModifyIpv6Bandwidth(#[\SensitiveParameter] Models\ModifyIpv6BandwidthRequest $request): Models\ModifyIpv6BandwidthResponse
    {
        return $this->call('ModifyIpv6Bandwidth', $request, Models\ModifyIpv6BandwidthResponse::class);
    }

    /**
     * 调整公网IPv6流量包。
     */
    public function ModifyIpv6TrafficPackage(#[\SensitiveParameter] Models\ModifyIpv6TrafficPackageRequest $request): Models\ModifyIpv6TrafficPackageResponse
    {
        return $this->call('ModifyIpv6TrafficPackage', $request, Models\ModifyIpv6TrafficPackageResponse::class);
    }

    /**
     * 变更网卡当前的主内网IPv4地址。
     */
    public function ReplaceNetworkInterfacePrimaryIpv4(#[\SensitiveParameter] Models\ReplaceNetworkInterfacePrimaryIpv4Request $request): Models\ReplaceNetworkInterfacePrimaryIpv4Response
    {
        return $this->call('ReplaceNetworkInterfacePrimaryIpv4', $request, Models\ReplaceNetworkInterfacePrimaryIpv4Response::class);
    }

    /**
     * 查询账户下的公网 IP 池信息，支持按 IP 池 ID、地域或名称进行筛选，支持分页查询。
     */
    public function DescribePools(#[\SensitiveParameter] Models\DescribePoolsRequest $request): Models\DescribePoolsResponse
    {
        return $this->call('DescribePools', $request, Models\DescribePoolsResponse::class);
    }

    /**
     * 支持售卖CIDR的节点信息。
     */
    public function DescribeCidrRegions(#[\SensitiveParameter] Models\DescribeCidrRegionsRequest $request): Models\DescribeCidrRegionsResponse
    {
        return $this->call('DescribeCidrRegions', $request, Models\DescribeCidrRegionsResponse::class);
    }

    /**
     * 查询 IPv4 CIDR 地址块售卖价格。
     */
    public function DescribeCidrPrice(#[\SensitiveParameter] Models\DescribeCidrPriceRequest $request): Models\DescribeCidrPriceResponse
    {
        return $this->call('DescribeCidrPrice', $request, Models\DescribeCidrPriceResponse::class);
    }

    /**
     * 查询IPv4 CIDR地址块列表。
     */
    public function DescribeCidrs(#[\SensitiveParameter] Models\DescribeCidrsRequest $request): Models\DescribeCidrsResponse
    {
        return $this->call('DescribeCidrs', $request, Models\DescribeCidrsResponse::class);
    }

    /**
     * 创建IPv4 CIDR地址段。
     */
    public function CreateCidr(#[\SensitiveParameter] Models\CreateCidrRequest $request): Models\CreateCidrResponse
    {
        return $this->call('CreateCidr', $request, Models\CreateCidrResponse::class);
    }

    /**
     * 修改IPv4 CIDR地址段的属性。 目前只能修改名称。
     */
    public function ModifyCidrAttribute(#[\SensitiveParameter] Models\ModifyCidrAttributeRequest $request): Models\ModifyCidrAttributeResponse
    {
        return $this->call('ModifyCidrAttribute', $request, Models\ModifyCidrAttributeResponse::class);
    }

    /**
     * 删除IPv4 CIDR地址段。
     */
    public function DeleteCidr(#[\SensitiveParameter] Models\DeleteCidrRequest $request): Models\DeleteCidrResponse
    {
        return $this->call('DeleteCidr', $request, Models\DeleteCidrResponse::class);
    }

    /**
     * 删除一个或多个IPv4 CIDR地址块。
     */
    public function DeleteCidrs(#[\SensitiveParameter] Models\DeleteCidrsRequest $request): Models\DeleteCidrsResponse
    {
        return $this->call('DeleteCidrs', $request, Models\DeleteCidrsResponse::class);
    }

    /**
     * 将一个处于回收站的IPv6 CIDR地址段恢复回正常。
     */
    public function RenewIpv6Cidr(#[\SensitiveParameter] Models\RenewIpv6CidrRequest $request): Models\RenewIpv6CidrResponse
    {
        return $this->call('RenewIpv6Cidr', $request, Models\RenewIpv6CidrResponse::class);
    }

    /**
     * 查询账户下的 IPv6 CIDR 地址块信息，支持按 CIDR ID、地域、名称、地址段筛选，支持标签过滤和分页查询。
     */
    public function DescribeIpv6Cidrs(#[\SensitiveParameter] Models\DescribeIpv6CidrsRequest $request): Models\DescribeIpv6CidrsResponse
    {
        return $this->call('DescribeIpv6Cidrs', $request, Models\DescribeIpv6CidrsResponse::class);
    }

    /**
     * 删除IPv6 CIDR地址块。
     */
    public function DeleteIpv6Cidr(#[\SensitiveParameter] Models\DeleteIpv6CidrRequest $request): Models\DeleteIpv6CidrResponse
    {
        return $this->call('DeleteIpv6Cidr', $request, Models\DeleteIpv6CidrResponse::class);
    }

    /**
     * 将一个处于回收站的IPv4 CIDR地址段恢复回正常。
     */
    public function RenewCidr(#[\SensitiveParameter] Models\RenewCidrRequest $request): Models\RenewCidrResponse
    {
        return $this->call('RenewCidr', $request, Models\RenewCidrResponse::class);
    }

    /**
     * 提交自带 IP 段（BYOIP）创建 CIDR。返回 RPKI/IRR 校验失败列表。
     */
    public function CreateByoip(#[\SensitiveParameter] Models\CreateByoipRequest $request): Models\CreateByoipResponse
    {
        return $this->call('CreateByoip', $request, Models\CreateByoipResponse::class);
    }

    /**
     * 返回支持售卖 BYOIP 的区域及对应网段、网络类型等信息。
     */
    public function DescribeByoipRegions(#[\SensitiveParameter] Models\DescribeByoipRegionsRequest $request): Models\DescribeByoipRegionsResponse
    {
        return $this->call('DescribeByoipRegions', $request, Models\DescribeByoipRegionsResponse::class);
    }

    /**
     * 根据宣告 IP 段、区域、线路类型等查询 BYOIP 价格。
     */
    public function DescribeByoipPrice(#[\SensitiveParameter] Models\DescribeByoipPriceRequest $request): Models\DescribeByoipPriceResponse
    {
        return $this->call('DescribeByoipPrice', $request, Models\DescribeByoipPriceResponse::class);
    }

    /**
     * 查询EIP支持的IP线路类型列表，可按节点过滤。
     */
    public function DescribeEipNetworkLineTypes(#[\SensitiveParameter] Models\DescribeEipNetworkLineTypesRequest $request): Models\DescribeEipNetworkLineTypesResponse
    {
        return $this->call('DescribeEipNetworkLineTypes', $request, Models\DescribeEipNetworkLineTypesResponse::class);
    }

    /**
     * 查询支持售卖EIP的区域信息。
     */
    public function DescribeEipRegions(#[\SensitiveParameter] Models\DescribeEipRegionsRequest $request): Models\DescribeEipRegionsResponse
    {
        return $this->call('DescribeEipRegions', $request, Models\DescribeEipRegionsResponse::class);
    }

    /**
     * 查询 EIP 支持的网络计费模式。
     */
    public function DescribeEipInternetChargeTypes(#[\SensitiveParameter] Models\DescribeEipInternetChargeTypesRequest $request): Models\DescribeEipInternetChargeTypesResponse
    {
        return $this->call('DescribeEipInternetChargeTypes', $request, Models\DescribeEipInternetChargeTypesResponse::class);
    }

    /**
     * 查询EIP支持的远程指向的节点信息。
     */
    public function DescribeEipRemoteRegions(#[\SensitiveParameter] Models\DescribeEipRemoteRegionsRequest $request): Models\DescribeEipRemoteRegionsResponse
    {
        return $this->call('DescribeEipRemoteRegions', $request, Models\DescribeEipRemoteRegionsResponse::class);
    }

    /**
     * 创建公网弹性IP询价。
     */
    public function DescribeEipPrice(#[\SensitiveParameter] Models\DescribeEipPriceRequest $request): Models\DescribeEipPriceResponse
    {
        return $this->call('DescribeEipPrice', $request, Models\DescribeEipPriceResponse::class);
    }

    /**
     * 指定条件查询已创建的弹性IPv4的信息。用户可以根据ID、名称等信息来搜索。
     */
    public function DescribeEips(#[\SensitiveParameter] Models\DescribeEipsRequest $request): Models\DescribeEipsResponse
    {
        return $this->call('DescribeEips', $request, Models\DescribeEipsResponse::class);
    }

    /**
     * 创建弹性公网IP。
     */
    public function CreateEips(#[\SensitiveParameter] Models\CreateEipsRequest $request): Models\CreateEipsResponse
    {
        return $this->call('CreateEips', $request, Models\CreateEipsResponse::class);
    }

    /**
     * 修改弹性公网IP属性。目前该接口支持修改名称。
     */
    public function ModifyEipAttribute(#[\SensitiveParameter] Models\ModifyEipAttributeRequest $request): Models\ModifyEipAttributeResponse
    {
        return $this->call('ModifyEipAttribute', $request, Models\ModifyEipAttributeResponse::class);
    }

    /**
     * 查询可与指定弹性公网 IP（EIP）进行绑定的弹性网卡（vNIC）及其内网 IPv4 地址列表。
     */
    public function AvailableLanIp(#[\SensitiveParameter] Models\AvailableLanIpRequest $request): Models\AvailableLanIpResponse
    {
        return $this->call('AvailableLanIp', $request, Models\AvailableLanIpResponse::class);
    }

    /**
     * 批量将弹性公网IP（EIP）绑定到同地域的云产品实例上。
     */
    public function AssociateEipAddress(#[\SensitiveParameter] Models\AssociateEipAddressRequest $request): Models\AssociateEipAddressResponse
    {
        return $this->call('AssociateEipAddress', $request, Models\AssociateEipAddressResponse::class);
    }

    /**
     * 将弹性公网IP（EIP）从绑定的云产品上解绑。
     */
    public function UnassociateEipAddress(#[\SensitiveParameter] Models\UnassociateEipAddressRequest $request): Models\UnassociateEipAddressResponse
    {
        return $this->call('UnassociateEipAddress', $request, Models\UnassociateEipAddressResponse::class);
    }

    /**
     * 替换一个或者多个弹性公网IP地址。
     */
    public function ReplaceEipAddress(#[\SensitiveParameter] Models\ReplaceEipAddressRequest $request): Models\ReplaceEipAddressResponse
    {
        return $this->call('ReplaceEipAddress', $request, Models\ReplaceEipAddressResponse::class);
    }

    /**
     * 变更弹性公网IP更网络计费模式。
     */
    public function ChangeEipInternetChargeType(#[\SensitiveParameter] Models\ChangeEipInternetChargeTypeRequest $request): Models\ChangeEipInternetChargeTypeResponse
    {
        return $this->call('ChangeEipInternetChargeType', $request, Models\ChangeEipInternetChargeTypeResponse::class);
    }

    /**
     * 调整弹性公网IP的带宽限速。
     */
    public function ModifyEipBandwidth(#[\SensitiveParameter] Models\ModifyEipBandwidthRequest $request): Models\ModifyEipBandwidthResponse
    {
        return $this->call('ModifyEipBandwidth', $request, Models\ModifyEipBandwidthResponse::class);
    }

    /**
     * 弹性公网IP（EIP）更换绑定模式。
     */
    public function ChangeEipBindType(#[\SensitiveParameter] Models\ChangeEipBindTypeRequest $request): Models\ChangeEipBindTypeResponse
    {
        return $this->call('ChangeEipBindType', $request, Models\ChangeEipBindTypeResponse::class);
    }

    /**
     * 弹性公网IP（EIP）探测配置。
     */
    public function ConfigEipProbe(#[\SensitiveParameter] Models\ConfigEipProbeRequest $request): Models\ConfigEipProbeResponse
    {
        return $this->call('ConfigEipProbe', $request, Models\ConfigEipProbeResponse::class);
    }

    /**
     * 指定IP作为出口IP。
     */
    public function ConfigEipEgressIp(#[\SensitiveParameter] Models\ConfigEipEgressIpRequest $request): Models\ConfigEipEgressIpResponse
    {
        return $this->call('ConfigEipEgressIp', $request, Models\ConfigEipEgressIpResponse::class);
    }

    /**
     * 删除指定的弹性公网IP。
     */
    public function DeleteEip(#[\SensitiveParameter] Models\DeleteEipRequest $request): Models\DeleteEipResponse
    {
        return $this->call('DeleteEip', $request, Models\DeleteEipResponse::class);
    }

    /**
     * 恢复弹性公网IP。
     */
    public function RenewEip(#[\SensitiveParameter] Models\RenewEipRequest $request): Models\RenewEipResponse
    {
        return $this->call('RenewEip', $request, Models\RenewEipResponse::class);
    }

    /**
     * 查询指定弹性公网 IP 在指定时间段内的流量监控数据，支持按统计粒度（step）聚合，可按出口公网 IP 过滤。
     */
    public function DescribeEipTraffic(#[\SensitiveParameter] Models\DescribeEipTrafficRequest $request): Models\DescribeEipTrafficResponse
    {
        return $this->call('DescribeEipTraffic', $request, Models\DescribeEipTrafficResponse::class);
    }

    /**
     * 查询一段时间的弹性公网IP监控指标数据。
     */
    public function DescribeEipMonitorData(#[\SensitiveParameter] Models\DescribeEipMonitorDataRequest $request): Models\DescribeEipMonitorDataResponse
    {
        return $this->call('DescribeEipMonitorData', $request, Models\DescribeEipMonitorDataResponse::class);
    }

    /**
     * 修改指定弹性公网IP的带宽限速模式。
     */
    public function ModifyEipBandwidthLimitMode(#[\SensitiveParameter] Models\ModifyEipBandwidthLimitModeRequest $request): Models\ModifyEipBandwidthLimitModeResponse
    {
        return $this->call('ModifyEipBandwidthLimitMode', $request, Models\ModifyEipBandwidthLimitModeResponse::class);
    }

    /**
     * 查询调整EIP带宽后的价格。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceModifyEipBandwidth(#[\SensitiveParameter] Models\InquiryPriceModifyEipBandwidthRequest $request): Models\InquiryPriceModifyEipBandwidthResponse
    {
        return $this->call('InquiryPriceModifyEipBandwidth', $request, Models\InquiryPriceModifyEipBandwidthResponse::class);
    }

    /**
     * 查询调整EIP流量包后的价格。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceModifyEipFlowPackage(#[\SensitiveParameter] Models\InquiryPriceModifyEipFlowPackageRequest $request): Models\InquiryPriceModifyEipFlowPackageResponse
    {
        return $this->call('InquiryPriceModifyEipFlowPackage', $request, Models\InquiryPriceModifyEipFlowPackageResponse::class);
    }

    /**
     * 查询变更EIP网络计费模式后的价格。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceChangeEipInternetChargeType(#[\SensitiveParameter] Models\InquiryPriceChangeEipInternetChargeTypeRequest $request): Models\InquiryPriceChangeEipInternetChargeTypeResponse
    {
        return $this->call('InquiryPriceChangeEipInternetChargeType', $request, Models\InquiryPriceChangeEipInternetChargeTypeResponse::class);
    }

    /**
     * 调整弹性公网IP流量包。
     */
    public function ModifyEipTrafficPackage(#[\SensitiveParameter] Models\ModifyEipTrafficPackageRequest $request): Models\ModifyEipTrafficPackageResponse
    {
        return $this->call('ModifyEipTrafficPackage', $request, Models\ModifyEipTrafficPackageResponse::class);
    }

    /**
     * 修改弹性公网IP（EIP）的自定义封堵阈值。
     */
    public function ModifyEipBlockThreshold(#[\SensitiveParameter] Models\ModifyEipBlockThresholdRequest $request): Models\ModifyEipBlockThresholdResponse
    {
        return $this->call('ModifyEipBlockThreshold', $request, Models\ModifyEipBlockThresholdResponse::class);
    }

    /**
     * 查询路由列表。用户可以根据ID、名称等信息来搜索Route信息。路由列表包括系统生成的以及用户创建的路由。
     */
    public function DescribeRoutes(#[\SensitiveParameter] Models\DescribeRoutesRequest $request): Models\DescribeRoutesResponse
    {
        return $this->call('DescribeRoutes', $request, Models\DescribeRoutesResponse::class);
    }

    /**
     * 创建一个自定义路由。
     */
    public function CreateRoute(#[\SensitiveParameter] Models\CreateRouteRequest $request): Models\CreateRouteResponse
    {
        return $this->call('CreateRoute', $request, Models\CreateRouteResponse::class);
    }

    /**
     * 修改路由的基本信息，目前只允许修改路由的名称。
     */
    public function ModifyRouteAttribute(#[\SensitiveParameter] Models\ModifyRouteAttributeRequest $request): Models\ModifyRouteAttributeResponse
    {
        return $this->call('ModifyRouteAttribute', $request, Models\ModifyRouteAttributeResponse::class);
    }

    /**
     * 删除一条自定义路由。
     */
    public function DeleteRoute(#[\SensitiveParameter] Models\DeleteRouteRequest $request): Models\DeleteRouteResponse
    {
        return $this->call('DeleteRoute', $request, Models\DeleteRouteResponse::class);
    }

    /**
     * 查询支持售卖内网跨区域带宽的区域信息。
     */
    public function DescribeCrossRegionBandwidthRegions(#[\SensitiveParameter] Models\DescribeCrossRegionBandwidthRegionsRequest $request): Models\DescribeCrossRegionBandwidthRegionsResponse
    {
        return $this->call('DescribeCrossRegionBandwidthRegions', $request, Models\DescribeCrossRegionBandwidthRegionsResponse::class);
    }

    /**
     * 创建内网跨区域带宽询价。
     */
    public function InquiryPriceCreateCrossRegionBandwidth(#[\SensitiveParameter] Models\InquiryPriceCreateCrossRegionBandwidthRequest $request): Models\InquiryPriceCreateCrossRegionBandwidthResponse
    {
        return $this->call('InquiryPriceCreateCrossRegionBandwidth', $request, Models\InquiryPriceCreateCrossRegionBandwidthResponse::class);
    }

    /**
     * 创建内网跨区域带宽。
     */
    public function CreateCrossRegionBandwidth(#[\SensitiveParameter] Models\CreateCrossRegionBandwidthRequest $request): Models\CreateCrossRegionBandwidthResponse
    {
        return $this->call('CreateCrossRegionBandwidth', $request, Models\CreateCrossRegionBandwidthResponse::class);
    }

    /**
     * 查询内网跨区域带宽列表。
     */
    public function DescribeCrossRegionBandwidth(#[\SensitiveParameter] Models\DescribeCrossRegionBandwidthRequest $request): Models\DescribeCrossRegionBandwidthResponse
    {
        return $this->call('DescribeCrossRegionBandwidth', $request, Models\DescribeCrossRegionBandwidthResponse::class);
    }

    /**
     * 调整内网跨区域带宽询价。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceModifyCrossRegionBandwidth(#[\SensitiveParameter] Models\InquiryPriceModifyCrossRegionBandwidthRequest $request): Models\InquiryPriceModifyCrossRegionBandwidthResponse
    {
        return $this->call('InquiryPriceModifyCrossRegionBandwidth', $request, Models\InquiryPriceModifyCrossRegionBandwidthResponse::class);
    }

    /**
     * 修改内网跨区域带宽属性（名称）。
     */
    public function ModifyCrossRegionBandwidthAttribute(#[\SensitiveParameter] Models\ModifyCrossRegionBandwidthAttributeRequest $request): Models\ModifyCrossRegionBandwidthAttributeResponse
    {
        return $this->call('ModifyCrossRegionBandwidthAttribute', $request, Models\ModifyCrossRegionBandwidthAttributeResponse::class);
    }

    /**
     * 调整内网跨区域带宽。
     */
    public function ModifyCrossRegionBandwidth(#[\SensitiveParameter] Models\ModifyCrossRegionBandwidthRequest $request): Models\ModifyCrossRegionBandwidthResponse
    {
        return $this->call('ModifyCrossRegionBandwidth', $request, Models\ModifyCrossRegionBandwidthResponse::class);
    }

    /**
     * 删除内网跨区域带宽。
     */
    public function DeleteCrossRegionBandwidth(#[\SensitiveParameter] Models\DeleteCrossRegionBandwidthRequest $request): Models\DeleteCrossRegionBandwidthResponse
    {
        return $this->call('DeleteCrossRegionBandwidth', $request, Models\DeleteCrossRegionBandwidthResponse::class);
    }

    /**
     * 恢复内网跨区域带宽。
     */
    public function RenewCrossRegionBandwidth(#[\SensitiveParameter] Models\RenewCrossRegionBandwidthRequest $request): Models\RenewCrossRegionBandwidthResponse
    {
        return $this->call('RenewCrossRegionBandwidth', $request, Models\RenewCrossRegionBandwidthResponse::class);
    }

    /**
     * 查询内网跨区域带宽监控指标数据。
     */
    public function DescribeCrossRegionBandwidthMonitorData(#[\SensitiveParameter] Models\DescribeCrossRegionBandwidthMonitorDataRequest $request): Models\DescribeCrossRegionBandwidthMonitorDataResponse
    {
        return $this->call('DescribeCrossRegionBandwidthMonitorData', $request, Models\DescribeCrossRegionBandwidthMonitorDataResponse::class);
    }

    /**
     * 查询已创建的DHCP选项集列表。
     */
    public function DescribeDhcpOptionsSets(#[\SensitiveParameter] Models\DescribeDhcpOptionsSetsRequest $request): Models\DescribeDhcpOptionsSetsResponse
    {
        return $this->call('DescribeDhcpOptionsSets', $request, Models\DescribeDhcpOptionsSetsResponse::class);
    }

    /**
     * 创建DHCP选项集。
     */
    public function CreateDhcpOptionsSet(#[\SensitiveParameter] Models\CreateDhcpOptionsSetRequest $request): Models\CreateDhcpOptionsSetResponse
    {
        return $this->call('CreateDhcpOptionsSet', $request, Models\CreateDhcpOptionsSetResponse::class);
    }

    /**
     * 修改DHCP选项集配置信息。
     */
    public function ModifyDhcpOptionsSetAttributes(#[\SensitiveParameter] Models\ModifyDhcpOptionsSetAttributesRequest $request): Models\ModifyDhcpOptionsSetAttributesResponse
    {
        return $this->call('ModifyDhcpOptionsSetAttributes', $request, Models\ModifyDhcpOptionsSetAttributesResponse::class);
    }

    /**
     * 将DHCP选项集关联到Subnet。
     */
    public function AttachDhcpOptionsSetToSubnet(#[\SensitiveParameter] Models\AttachDhcpOptionsSetToSubnetRequest $request): Models\AttachDhcpOptionsSetToSubnetResponse
    {
        return $this->call('AttachDhcpOptionsSetToSubnet', $request, Models\AttachDhcpOptionsSetToSubnetResponse::class);
    }

    /**
     * 将DHCP选项集与Subnet取消关联。
     */
    public function DetachDhcpOptionsSetFromSubnet(#[\SensitiveParameter] Models\DetachDhcpOptionsSetFromSubnetRequest $request): Models\DetachDhcpOptionsSetFromSubnetResponse
    {
        return $this->call('DetachDhcpOptionsSetFromSubnet', $request, Models\DetachDhcpOptionsSetFromSubnetResponse::class);
    }

    /**
     * 删除DHCP选项集。
     */
    public function DeleteDhcpOptionsSet(#[\SensitiveParameter] Models\DeleteDhcpOptionsSetRequest $request): Models\DeleteDhcpOptionsSetResponse
    {
        return $this->call('DeleteDhcpOptionsSet', $request, Models\DeleteDhcpOptionsSetResponse::class);
    }

    /**
     * 在某节点为VPC创建一个边界网关。
     */
    public function CreateBorderGateway(#[\SensitiveParameter] Models\CreateBorderGatewayRequest $request): Models\CreateBorderGatewayResponse
    {
        return $this->call('CreateBorderGateway', $request, Models\CreateBorderGatewayResponse::class);
    }

    /**
     * 查询边界网关列表。
     */
    public function DescribeBorderGateways(#[\SensitiveParameter] Models\DescribeBorderGatewaysRequest $request): Models\DescribeBorderGatewaysResponse
    {
        return $this->call('DescribeBorderGateways', $request, Models\DescribeBorderGatewaysResponse::class);
    }

    /**
     * 修改边界网关的ASN。
     */
    public function ModifyBorderGatewayAsn(#[\SensitiveParameter] Models\ModifyBorderGatewayAsnRequest $request): Models\ModifyBorderGatewayAsnResponse
    {
        return $this->call('ModifyBorderGatewayAsn', $request, Models\ModifyBorderGatewayAsnResponse::class);
    }

    /**
     * 修改边界网关的属性，包括名称，路由级别，子网宣告控制等。
     */
    public function ModifyBorderGatewaysAttribute(#[\SensitiveParameter] Models\ModifyBorderGatewaysAttributeRequest $request): Models\ModifyBorderGatewaysAttributeResponse
    {
        return $this->call('ModifyBorderGatewaysAttribute', $request, Models\ModifyBorderGatewaysAttributeResponse::class);
    }

    /**
     * 获取可绑定边界网关的NAT网关列表。
     */
    public function DescribeAvailableNats(#[\SensitiveParameter] Models\DescribeAvailableNatsRequest $request): Models\DescribeAvailableNatsResponse
    {
        return $this->call('DescribeAvailableNats', $request, Models\DescribeAvailableNatsResponse::class);
    }

    /**
     * 边界网关绑定NAT网关。
     */
    public function AssignBorderGateway(#[\SensitiveParameter] Models\AssignBorderGatewayRequest $request): Models\AssignBorderGatewayResponse
    {
        return $this->call('AssignBorderGateway', $request, Models\AssignBorderGatewayResponse::class);
    }

    /**
     * 解除指定边界网关（ZBG）与 NAT 网关的绑定关系，解绑后边界网关将不再为该 NAT 网关广播路由。
     */
    public function UnassignBorderGateway(#[\SensitiveParameter] Models\UnassignBorderGatewayRequest $request): Models\UnassignBorderGatewayResponse
    {
        return $this->call('UnassignBorderGateway', $request, Models\UnassignBorderGatewayResponse::class);
    }

    /**
     * 边界网关绑定自定义路由。即自定义路由发布到zbg网关。
     */
    public function AssignBorderGatewayRoute(#[\SensitiveParameter] Models\AssignBorderGatewayRouteRequest $request): Models\AssignBorderGatewayRouteResponse
    {
        return $this->call('AssignBorderGatewayRoute', $request, Models\AssignBorderGatewayRouteResponse::class);
    }

    /**
     * 边界网关路由宣告中移除指定的自定义路由。
     */
    public function UnassignBorderGatewayRoute(#[\SensitiveParameter] Models\UnassignBorderGatewayRouteRequest $request): Models\UnassignBorderGatewayRouteResponse
    {
        return $this->call('UnassignBorderGatewayRoute', $request, Models\UnassignBorderGatewayRouteResponse::class);
    }

    /**
     * 删除一个指定的边界网关。
     */
    public function DeleteBorderGateway(#[\SensitiveParameter] Models\DeleteBorderGatewayRequest $request): Models\DeleteBorderGatewayResponse
    {
        return $this->call('DeleteBorderGateway', $request, Models\DeleteBorderGatewayResponse::class);
    }

    /**
     * 查询当前账号下边界网关可支持互联的节点与数据中心信息。边界网关可绑定 CloudRouter 以实现 VPC 的 L3 互联，本接口返回支持此功能的节点列表，可按节点ID或数据中心进行过滤。
     */
    public function DescribeInterconnectBorderGatewayRegions(#[\SensitiveParameter] Models\DescribeInterconnectBorderGatewayRegionsRequest $request): Models\DescribeInterconnectBorderGatewayRegionsResponse
    {
        return $this->call('DescribeInterconnectBorderGatewayRegions', $request, Models\DescribeInterconnectBorderGatewayRegionsResponse::class);
    }

    /**
     * 查询满足条件的非托管出口IP列表，返回IP基础信息及带宽限速模式。
     */
    public function DescribeUnmanagedEgressIps(#[\SensitiveParameter] Models\DescribeUnmanagedEgressIpsRequest $request): Models\DescribeUnmanagedEgressIpsResponse
    {
        return $this->call('DescribeUnmanagedEgressIps', $request, Models\DescribeUnmanagedEgressIpsResponse::class);
    }

    /**
     * 修改指定非托管出口IP的带宽限速模式。
     */
    public function ModifyUnmanagedEgressIpBandwidthLimitMode(#[\SensitiveParameter] Models\ModifyUnmanagedEgressIpBandwidthLimitModeRequest $request): Models\ModifyUnmanagedEgressIpBandwidthLimitModeResponse
    {
        return $this->call('ModifyUnmanagedEgressIpBandwidthLimitMode', $request, Models\ModifyUnmanagedEgressIpBandwidthLimitModeResponse::class);
    }

    /**
     * 查询调整非托管出口IP带宽后的价格。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceModifyUnmanagedEgressIpBandwidth(#[\SensitiveParameter] Models\InquiryPriceModifyUnmanagedEgressIpBandwidthRequest $request): Models\InquiryPriceModifyUnmanagedEgressIpBandwidthResponse
    {
        return $this->call('InquiryPriceModifyUnmanagedEgressIpBandwidth', $request, Models\InquiryPriceModifyUnmanagedEgressIpBandwidthResponse::class);
    }

    /**
     * 查询变更非托管出口IP网络计费模式后的价格。同时通过 previousPrices 返回变更前各计费项当前生效的价格，用于对比出哪些计费项发生了调价。
     */
    public function InquiryPriceChangeUnmanagedEgressIpInternetChargeType(#[\SensitiveParameter] Models\InquiryPriceChangeUnmanagedEgressIpInternetChargeTypeRequest $request): Models\InquiryPriceChangeUnmanagedEgressIpInternetChargeTypeResponse
    {
        return $this->call('InquiryPriceChangeUnmanagedEgressIpInternetChargeType', $request, Models\InquiryPriceChangeUnmanagedEgressIpInternetChargeTypeResponse::class);
    }

    /**
     * 查询一个或多个QoS策略组的详细信息。
     */
    public function DescribeQosPolicyGroups(#[\SensitiveParameter] Models\DescribeQosPolicyGroupsRequest $request): Models\DescribeQosPolicyGroupsResponse
    {
        return $this->call('DescribeQosPolicyGroups', $request, Models\DescribeQosPolicyGroupsResponse::class);
    }

    /**
     * 创建一个QoS策略组，将EIP、IPv6或UNMANAGED出口IP纳入同一策略组实施共享带宽限速。
     */
    public function CreateQosPolicyGroup(#[\SensitiveParameter] Models\CreateQosPolicyGroupRequest $request): Models\CreateQosPolicyGroupResponse
    {
        return $this->call('CreateQosPolicyGroup', $request, Models\CreateQosPolicyGroupResponse::class);
    }

    /**
     * 修改QoS策略组的名称或带宽限制。
     */
    public function ModifyQosPolicyGroup(#[\SensitiveParameter] Models\ModifyQosPolicyGroupRequest $request): Models\ModifyQosPolicyGroupResponse
    {
        return $this->call('ModifyQosPolicyGroup', $request, Models\ModifyQosPolicyGroupResponse::class);
    }

    /**
     * 向QoS策略组中添加EIP、IPv6或UNMANAGED出口IP。
     */
    public function AddQosPolicyGroupMembers(#[\SensitiveParameter] Models\AddQosPolicyGroupMembersRequest $request): Models\AddQosPolicyGroupMembersResponse
    {
        return $this->call('AddQosPolicyGroupMembers', $request, Models\AddQosPolicyGroupMembersResponse::class);
    }

    /**
     * 从QoS策略组中移除成员。
     */
    public function RemoveQosPolicyGroupMembers(#[\SensitiveParameter] Models\RemoveQosPolicyGroupMembersRequest $request): Models\RemoveQosPolicyGroupMembersResponse
    {
        return $this->call('RemoveQosPolicyGroupMembers', $request, Models\RemoveQosPolicyGroupMembersResponse::class);
    }

    /**
     * 删除一个QoS策略组。删除前需确保策略组内无成员。
     */
    public function DeleteQosPolicyGroup(#[\SensitiveParameter] Models\DeleteQosPolicyGroupRequest $request): Models\DeleteQosPolicyGroupResponse
    {
        return $this->call('DeleteQosPolicyGroup', $request, Models\DeleteQosPolicyGroupResponse::class);
    }

    /**
     * 查询QoS策略组的聚合流量监控数据。
     */
    public function DescribeQosPolicyGroupTraffic(#[\SensitiveParameter] Models\DescribeQosPolicyGroupTrafficRequest $request): Models\DescribeQosPolicyGroupTrafficResponse
    {
        return $this->call('DescribeQosPolicyGroupTraffic', $request, Models\DescribeQosPolicyGroupTrafficResponse::class);
    }

    /**
     * 查询私有网络（VPC）列表，用户可以根据 VPC ID、VPC 名称等信息来筛选过滤VPC信息。
     */
    public function DescribeVpcs(#[\SensitiveParameter] Models\DescribeVpcsRequest $request): Models\DescribeVpcsResponse
    {
        return $this->call('DescribeVpcs', $request, Models\DescribeVpcsResponse::class);
    }

    /**
     * 创建全球VPC。
     */
    public function CreateVpc(#[\SensitiveParameter] Models\CreateVpcRequest $request): Models\CreateVpcResponse
    {
        return $this->call('CreateVpc', $request, Models\CreateVpcResponse::class);
    }

    /**
     * 修改私有网络（VPC）的相关属性。
     */
    public function ModifyVpcAttribute(#[\SensitiveParameter] Models\ModifyVpcAttributeRequest $request): Models\ModifyVpcAttributeResponse
    {
        return $this->call('ModifyVpcAttribute', $request, Models\ModifyVpcAttributeResponse::class);
    }

    /**
     * 修改一个或多个VPC的属性。该接口只支持修改VPC的名称。
     */
    public function ModifyVpcsAttribute(#[\SensitiveParameter] Models\ModifyVpcsAttributeRequest $request): Models\ModifyVpcsAttributeResponse
    {
        return $this->call('ModifyVpcsAttribute', $request, Models\ModifyVpcsAttributeResponse::class);
    }

    /**
     * 删除VPC。
     */
    public function DeleteVpc(#[\SensitiveParameter] Models\DeleteVpcRequest $request): Models\DeleteVpcResponse
    {
        return $this->call('DeleteVpc', $request, Models\DeleteVpcResponse::class);
    }

    /**
     * 查询支持创建子网区域以及是否IPv6。
     */
    public function DescribeSubnetRegions(#[\SensitiveParameter] Models\DescribeSubnetRegionsRequest $request): Models\DescribeSubnetRegionsResponse
    {
        return $this->call('DescribeSubnetRegions', $request, Models\DescribeSubnetRegionsResponse::class);
    }

    /**
     * 查询子网列表信息。可以根据子网ID, 名称等信息筛选查询子网。
     */
    public function DescribeSubnets(#[\SensitiveParameter] Models\DescribeSubnetsRequest $request): Models\DescribeSubnetsResponse
    {
        return $this->call('DescribeSubnets', $request, Models\DescribeSubnetsResponse::class);
    }

    /**
     * 创建子网。
     */
    public function CreateSubnet(#[\SensitiveParameter] Models\CreateSubnetRequest $request): Models\CreateSubnetResponse
    {
        return $this->call('CreateSubnet', $request, Models\CreateSubnetResponse::class);
    }

    /**
     * 修改子网属性。包括名称，CIDR等。
     */
    public function ModifySubnetAttribute(#[\SensitiveParameter] Models\ModifySubnetAttributeRequest $request): Models\ModifySubnetAttributeResponse
    {
        return $this->call('ModifySubnetAttribute', $request, Models\ModifySubnetAttributeResponse::class);
    }

    /**
     * 批量修改子网的属性。
     */
    public function ModifySubnetsAttribute(#[\SensitiveParameter] Models\ModifySubnetsAttributeRequest $request): Models\ModifySubnetsAttributeResponse
    {
        return $this->call('ModifySubnetsAttribute', $request, Models\ModifySubnetsAttributeResponse::class);
    }

    /**
     * 修改指定子网的 IP 地址堆栈类型（IPv4 / IPv4_IPv6 / IPv6）。变更为双栈或纯 IPv6 时须配置 IPv6 类型及对应的 CIDR 地址块。
     */
    public function ModifySubnetStackType(#[\SensitiveParameter] Models\ModifySubnetStackTypeRequest $request): Models\ModifySubnetStackTypeResponse
    {
        return $this->call('ModifySubnetStackType', $request, Models\ModifySubnetStackTypeResponse::class);
    }

    /**
     * 删除一个子网。
     */
    public function DeleteSubnet(#[\SensitiveParameter] Models\DeleteSubnetRequest $request): Models\DeleteSubnetResponse
    {
        return $this->call('DeleteSubnet', $request, Models\DeleteSubnetResponse::class);
    }

    /**
     * 在同一个VPC下批量创建多个子网。
     */
    public function CreateSubnets(#[\SensitiveParameter] Models\CreateSubnetsRequest $request): Models\CreateSubnetsResponse
    {
        return $this->call('CreateSubnets', $request, Models\CreateSubnetsResponse::class);
    }

    /**
     * 删除一个或多个子网。
     */
    public function DeleteSubnets(#[\SensitiveParameter] Models\DeleteSubnetsRequest $request): Models\DeleteSubnetsResponse
    {
        return $this->call('DeleteSubnets', $request, Models\DeleteSubnetsResponse::class);
    }

    /**
     * 支持售卖NAT网关的区域信息。
     */
    public function DescribeNatGatewayRegions(#[\SensitiveParameter] Models\DescribeNatGatewayRegionsRequest $request): Models\DescribeNatGatewayRegionsResponse
    {
        return $this->call('DescribeNatGatewayRegions', $request, Models\DescribeNatGatewayRegionsResponse::class);
    }

    /**
     * 获取可绑定NAT的边界网关。
     */
    public function DescribeAvailableBorderGateway(#[\SensitiveParameter] Models\DescribeAvailableBorderGatewayRequest $request): Models\DescribeAvailableBorderGatewayResponse
    {
        return $this->call('DescribeAvailableBorderGateway', $request, Models\DescribeAvailableBorderGatewayResponse::class);
    }

    /**
     * 查询创建NAT网关的价格。
     */
    public function InquiryPriceCreateNatGateway(#[\SensitiveParameter] Models\InquiryPriceCreateNatGatewayRequest $request): Models\InquiryPriceCreateNatGatewayResponse
    {
        return $this->call('InquiryPriceCreateNatGateway', $request, Models\InquiryPriceCreateNatGatewayResponse::class);
    }

    /**
     * 创建NAT网关。
     */
    public function CreateNatGateway(#[\SensitiveParameter] Models\CreateNatGatewayRequest $request): Models\CreateNatGatewayResponse
    {
        return $this->call('CreateNatGateway', $request, Models\CreateNatGatewayResponse::class);
    }

    /**
     * 查询NAT网关列表。
     */
    public function DescribeNatGateways(#[\SensitiveParameter] Models\DescribeNatGatewaysRequest $request): Models\DescribeNatGatewaysResponse
    {
        return $this->call('DescribeNatGateways', $request, Models\DescribeNatGatewaysResponse::class);
    }

    /**
     * 查询NAT网关详情规则表。
     */
    public function DescribeNatGatewayDetail(#[\SensitiveParameter] Models\DescribeNatGatewayDetailRequest $request): Models\DescribeNatGatewayDetailResponse
    {
        return $this->call('DescribeNatGatewayDetail', $request, Models\DescribeNatGatewayDetailResponse::class);
    }

    /**
     * 修改指定 NAT 网关的名称、关联子网、ICMP 回应及安全组配置。
     */
    public function ModifyNatGatewayAttribute(#[\SensitiveParameter] Models\ModifyNatGatewayAttributeRequest $request): Models\ModifyNatGatewayAttributeResponse
    {
        return $this->call('ModifyNatGatewayAttribute', $request, Models\ModifyNatGatewayAttributeResponse::class);
    }

    /**
     * 续费一个指定的NAT网关。
     */
    public function RenewNatGateway(#[\SensitiveParameter] Models\RenewNatGatewayRequest $request): Models\RenewNatGatewayResponse
    {
        return $this->call('RenewNatGateway', $request, Models\RenewNatGatewayResponse::class);
    }

    /**
     * 删除一个指定的NAT网关。
     */
    public function DeleteNatGateway(#[\SensitiveParameter] Models\DeleteNatGatewayRequest $request): Models\DeleteNatGatewayResponse
    {
        return $this->call('DeleteNatGateway', $request, Models\DeleteNatGatewayResponse::class);
    }

    /**
     * 创建SNAT规则。
     */
    public function CreateSnatEntry(#[\SensitiveParameter] Models\CreateSnatEntryRequest $request): Models\CreateSnatEntryResponse
    {
        return $this->call('CreateSnatEntry', $request, Models\CreateSnatEntryResponse::class);
    }

    /**
     * 修改SNAT规则。
     */
    public function ModifySnatEntry(#[\SensitiveParameter] Models\ModifySnatEntryRequest $request): Models\ModifySnatEntryResponse
    {
        return $this->call('ModifySnatEntry', $request, Models\ModifySnatEntryResponse::class);
    }

    /**
     * 删除SNAT规则。
     */
    public function DeleteSnatEntry(#[\SensitiveParameter] Models\DeleteSnatEntryRequest $request): Models\DeleteSnatEntryResponse
    {
        return $this->call('DeleteSnatEntry', $request, Models\DeleteSnatEntryResponse::class);
    }

    /**
     * 创建DNAT规则。
     */
    public function CreateDnatEntry(#[\SensitiveParameter] Models\CreateDnatEntryRequest $request): Models\CreateDnatEntryResponse
    {
        return $this->call('CreateDnatEntry', $request, Models\CreateDnatEntryResponse::class);
    }

    /**
     * 修改DNAT规则。
     */
    public function ModifyDnatEntry(#[\SensitiveParameter] Models\ModifyDnatEntryRequest $request): Models\ModifyDnatEntryResponse
    {
        return $this->call('ModifyDnatEntry', $request, Models\ModifyDnatEntryResponse::class);
    }

    /**
     * 删除DNAT规则。
     */
    public function DeleteDnatEntry(#[\SensitiveParameter] Models\DeleteDnatEntryRequest $request): Models\DeleteDnatEntryResponse
    {
        return $this->call('DeleteDnatEntry', $request, Models\DeleteDnatEntryResponse::class);
    }

    /**
     * 创建防护策略。
     */
    public function CreatePolicy(#[\SensitiveParameter] Models\CreatePolicyRequest $request): Models\CreatePolicyResponse
    {
        return $this->call('CreatePolicy', $request, Models\CreatePolicyResponse::class);
    }

    /**
     * 查询账户下的 DDoS 防护策略信息，支持按策略 ID、策略名称筛选，支持标签过滤和分页查询。
     */
    public function DescribePolicys(#[\SensitiveParameter] Models\DescribePolicysRequest $request): Models\DescribePolicysResponse
    {
        return $this->call('DescribePolicys', $request, Models\DescribePolicysResponse::class);
    }

    /**
     * 查询指定 DDoS 防护策略的详细配置，包括黑白名单、封禁协议、区域封禁、特征过滤及流量控制规则等。
     */
    public function DescribePolicyDetail(#[\SensitiveParameter] Models\DescribePolicyDetailRequest $request): Models\DescribePolicyDetailResponse
    {
        return $this->call('DescribePolicyDetail', $request, Models\DescribePolicyDetailResponse::class);
    }

    /**
     * 修改指定 DDoS 防护策略的配置，包括策略名称、IP 黑白名单、封禁协议、区域封禁、特征过滤及流量控制规则。
     */
    public function ModifyPolicy(#[\SensitiveParameter] Models\ModifyPolicyRequest $request): Models\ModifyPolicyResponse
    {
        return $this->call('ModifyPolicy', $request, Models\ModifyPolicyResponse::class);
    }

    /**
     * 防护对象关联防护策略。
     */
    public function AttachToPolicy(#[\SensitiveParameter] Models\AttachToPolicyRequest $request): Models\AttachToPolicyResponse
    {
        return $this->call('AttachToPolicy', $request, Models\AttachToPolicyResponse::class);
    }

    /**
     * 防护对象取消关联防护策略。
     */
    public function DetachFromPolicy(#[\SensitiveParameter] Models\DetachFromPolicyRequest $request): Models\DetachFromPolicyResponse
    {
        return $this->call('DetachFromPolicy', $request, Models\DetachFromPolicyResponse::class);
    }

    /**
     * 查询 DDoS 防护策略中区域封禁功能支持的可选地区列表，用于配置防护策略 `blockRegions` 参数前的参考。
     */
    public function DescribePolicyRegions(#[\SensitiveParameter] Models\DescribePolicyRegionsRequest $request): Models\DescribePolicyRegionsResponse
    {
        return $this->call('DescribePolicyRegions', $request, Models\DescribePolicyRegionsResponse::class);
    }

    /**
     * 查询 DDoS 防护策略中 UDP 反射攻击防护功能的默认封禁源端口列表，用于配置防护策略 `reflectUdpPort` 参数前的参考。
     */
    public function DescribeReflectUdpPortOptions(#[\SensitiveParameter] Models\DescribeReflectUdpPortOptionsRequest $request): Models\DescribeReflectUdpPortOptionsResponse
    {
        return $this->call('DescribeReflectUdpPortOptions', $request, Models\DescribeReflectUdpPortOptionsResponse::class);
    }

    /**
     * 删除防护策略。
     */
    public function DeletePolicy(#[\SensitiveParameter] Models\DeletePolicyRequest $request): Models\DeletePolicyResponse
    {
        return $this->call('DeletePolicy', $request, Models\DeletePolicyResponse::class);
    }

    /**
     * 获取攻击事件详情。
     */
    public function DescribeDDosEventDetail(#[\SensitiveParameter] Models\DescribeDDosEventDetailRequest $request): Models\DescribeDDosEventDetailResponse
    {
        return $this->call('DescribeDDosEventDetail', $request, Models\DescribeDDosEventDetailResponse::class);
    }

    /**
     * 获取攻击事件列表。
     */
    public function DescribeDDosAllEventList(#[\SensitiveParameter] Models\DescribeDDosAllEventListRequest $request): Models\DescribeDDosAllEventListResponse
    {
        return $this->call('DescribeDDosAllEventList', $request, Models\DescribeDDosAllEventListResponse::class);
    }

    /**
     * 查询账户下的安全组信息，支持按安全组 ID 或名称进行筛选，支持分页查询。
     */
    public function DescribeSecurityGroups(#[\SensitiveParameter] Models\DescribeSecurityGroupsRequest $request): Models\DescribeSecurityGroupsResponse
    {
        return $this->call('DescribeSecurityGroups', $request, Models\DescribeSecurityGroupsResponse::class);
    }

    /**
     * 创建一个安全组。
     */
    public function CreateSecurityGroup(#[\SensitiveParameter] Models\CreateSecurityGroupRequest $request): Models\CreateSecurityGroupResponse
    {
        return $this->call('CreateSecurityGroup', $request, Models\CreateSecurityGroupResponse::class);
    }

    /**
     * 修改安全组的属性（目前只支持修改安全组的名称）。
     */
    public function ModifySecurityGroupsAttribute(#[\SensitiveParameter] Models\ModifySecurityGroupsAttributeRequest $request): Models\ModifySecurityGroupsAttributeResponse
    {
        return $this->call('ModifySecurityGroupsAttribute', $request, Models\ModifySecurityGroupsAttributeResponse::class);
    }

    /**
     * 删除一个安全组。
     */
    public function DeleteSecurityGroup(#[\SensitiveParameter] Models\DeleteSecurityGroupRequest $request): Models\DeleteSecurityGroupResponse
    {
        return $this->call('DeleteSecurityGroup', $request, Models\DeleteSecurityGroupResponse::class);
    }

    /**
     * 查询指定安全组内的规则。
     */
    public function DescribeSecurityGroupRule(#[\SensitiveParameter] Models\DescribeSecurityGroupRuleRequest $request): Models\DescribeSecurityGroupRuleResponse
    {
        return $this->call('DescribeSecurityGroupRule', $request, Models\DescribeSecurityGroupRuleResponse::class);
    }

    /**
     * 配置安全组规则。
     */
    public function ConfigureSecurityGroupRules(#[\SensitiveParameter] Models\ConfigureSecurityGroupRulesRequest $request): Models\ConfigureSecurityGroupRulesResponse
    {
        return $this->call('ConfigureSecurityGroupRules', $request, Models\ConfigureSecurityGroupRulesResponse::class);
    }

    /**
     * VPC更换绑定安全组。
     */
    public function AssignSecurityGroupVpc(#[\SensitiveParameter] Models\AssignSecurityGroupVpcRequest $request): Models\AssignSecurityGroupVpcResponse
    {
        return $this->call('AssignSecurityGroupVpc', $request, Models\AssignSecurityGroupVpcResponse::class);
    }

    /**
     * VPC解绑安全组。
     */
    public function UnAssignSecurityGroupVpc(#[\SensitiveParameter] Models\UnAssignSecurityGroupVpcRequest $request): Models\UnAssignSecurityGroupVpcResponse
    {
        return $this->call('UnAssignSecurityGroupVpc', $request, Models\UnAssignSecurityGroupVpcResponse::class);
    }

    /**
     * 创建置放组。
     */
    public function CreatePlacementGroup(#[\SensitiveParameter] Models\CreatePlacementGroupRequest $request): Models\CreatePlacementGroupResponse
    {
        return $this->call('CreatePlacementGroup', $request, Models\CreatePlacementGroupResponse::class);
    }

    /**
     * 修改置放组的名称、分区数、亲和度等属性。
     */
    public function ModifyPlacementGroupAttributes(#[\SensitiveParameter] Models\ModifyPlacementGroupAttributesRequest $request): Models\ModifyPlacementGroupAttributesResponse
    {
        return $this->call('ModifyPlacementGroupAttributes', $request, Models\ModifyPlacementGroupAttributesResponse::class);
    }

    /**
     * 查询一个或多个置放组的信息。用户可以根据置放组ID、名称或可用区等条件来查询置放组的详细信息。
     */
    public function DescribePlacementGroups(#[\SensitiveParameter] Models\DescribePlacementGroupsRequest $request): Models\DescribePlacementGroupsResponse
    {
        return $this->call('DescribePlacementGroups', $request, Models\DescribePlacementGroupsResponse::class);
    }

    /**
     * 删除一个或多个置放组。删除后置放组内所有实例解除放置策略约束。
     */
    public function DeletePlacementGroups(#[\SensitiveParameter] Models\DeletePlacementGroupsRequest $request): Models\DeletePlacementGroupsResponse
    {
        return $this->call('DeletePlacementGroups', $request, Models\DeletePlacementGroupsResponse::class);
    }

    /**
     * 将实例加入置放组、从一个置放组迁移到另一个、或从置放组移除。
     */
    public function ModifyInstancePlacement(#[\SensitiveParameter] Models\ModifyInstancePlacementRequest $request): Models\ModifyInstancePlacementResponse
    {
        return $this->call('ModifyInstancePlacement', $request, Models\ModifyInstancePlacementResponse::class);
    }

    /**
     * 创建一个高可用虚拟IP。
     */
    public function CreateHaVip(#[\SensitiveParameter] Models\CreateHaVipRequest $request): Models\CreateHaVipResponse
    {
        return $this->call('CreateHaVip', $request, Models\CreateHaVipResponse::class);
    }

    /**
     * 查询一个或多个高可用虚拟IP的详细信息。
     */
    public function DescribeHaVips(#[\SensitiveParameter] Models\DescribeHaVipsRequest $request): Models\DescribeHaVipsResponse
    {
        return $this->call('DescribeHaVips', $request, Models\DescribeHaVipsResponse::class);
    }

    /**
     * 修改高可用虚拟IP的名称或绑定的安全组。
     */
    public function ModifyHaVipAttribute(#[\SensitiveParameter] Models\ModifyHaVipAttributeRequest $request): Models\ModifyHaVipAttributeResponse
    {
        return $this->call('ModifyHaVipAttribute', $request, Models\ModifyHaVipAttributeResponse::class);
    }

    /**
     * 删除高可用虚拟IP。
     */
    public function DeleteHaVip(#[\SensitiveParameter] Models\DeleteHaVipRequest $request): Models\DeleteHaVipResponse
    {
        return $this->call('DeleteHaVip', $request, Models\DeleteHaVipResponse::class);
    }

    /**
     * 将高可用虚拟IP绑定到一台ZEC实例。
     */
    public function AssociateHaVip(#[\SensitiveParameter] Models\AssociateHaVipRequest $request): Models\AssociateHaVipResponse
    {
        return $this->call('AssociateHaVip', $request, Models\AssociateHaVipResponse::class);
    }

    /**
     * 将高可用虚拟IP从实例解绑。
     */
    public function UnassociateHaVip(#[\SensitiveParameter] Models\UnassociateHaVipRequest $request): Models\UnassociateHaVipResponse
    {
        return $this->call('UnassociateHaVip', $request, Models\UnassociateHaVipResponse::class);
    }
}
