<?php

declare(strict_types=1);

namespace ZenlayerCloud\Laravel\Vm\V20260401;

use ZenlayerCloud\Laravel\Common\AbstractClient;

/**
 * Zenlayer Cloud Virtual Machine (VM) client (API version 2026-04-01).
 *
 * Each public method maps 1:1 to an Action name documented at
 * https://docs.console.zenlayer.com/api-reference/cn. Method names are
 * intentionally PascalCase to keep that mapping unambiguous when copy-
 * pasting examples between the API reference and PHP code.
 *
 * @generated by bin/codegen.php — do not edit by hand.
 */
class VmClient extends AbstractClient
{
    protected function service(): string
    {
        return 'vm';
    }

    protected function apiVersion(): string
    {
        return '2026-04-01';
    }

    /**
     * 查询可用地区。
     */
    public function DescribeZones(Models\DescribeZonesRequest $request): Models\DescribeZonesResponse
    {
        return $this->call('DescribeZones', $request, Models\DescribeZonesResponse::class);
    }

    /**
     * 创建一台虚拟机实例询价。
     */
    public function InquiryPriceCreateInstance(Models\InquiryPriceCreateInstanceRequest $request): Models\InquiryPriceCreateInstanceResponse
    {
        return $this->call('InquiryPriceCreateInstance', $request, Models\InquiryPriceCreateInstanceResponse::class);
    }

    /**
     * 查询售卖可用区的机型信息。
     */
    public function DescribeZoneInstanceConfigInfos(Models\DescribeZoneInstanceConfigInfosRequest $request): Models\DescribeZoneInstanceConfigInfosResponse
    {
        return $this->call('DescribeZoneInstanceConfigInfos', $request, Models\DescribeZoneInstanceConfigInfosResponse::class);
    }

    /**
     * 创建一个或多个指定配置的虚拟机实例。
     */
    public function CreateInstances(Models\CreateInstancesRequest $request): Models\CreateInstancesResponse
    {
        return $this->call('CreateInstances', $request, Models\CreateInstancesResponse::class);
    }

    /**
     * 将虚拟机实例操作系统的密码重置为用户指定的密码。
     */
    public function ResetInstancesPassword(Models\ResetInstancesPasswordRequest $request): Models\ResetInstancesPasswordResponse
    {
        return $this->call('ResetInstancesPassword', $request, Models\ResetInstancesPasswordResponse::class);
    }

    /**
     * 重装一台虚拟机实例上的操作系统。
     */
    public function ResetInstance(Models\ResetInstanceRequest $request): Models\ResetInstanceResponse
    {
        return $this->call('ResetInstance', $request, Models\ResetInstanceResponse::class);
    }

    /**
     * 修改虚拟机实例所属的资源组。
     */
    public function ModifyInstancesResourceGroup(Models\ModifyInstancesResourceGroupRequest $request): Models\ModifyInstancesResourceGroupResponse
    {
        return $this->call('ModifyInstancesResourceGroup', $request, Models\ModifyInstancesResourceGroupResponse::class);
    }

    /**
     * 查询一台或多台虚拟机实例的信息。用户可以根据实例ID、实例名称或者实例计费模式等条件来查询实例的详细信息。
     */
    public function DescribeInstances(Models\DescribeInstancesRequest $request): Models\DescribeInstancesResponse
    {
        return $this->call('DescribeInstances', $request, Models\DescribeInstancesResponse::class);
    }

    /**
     * 查询一台或多台虚拟机实例的状态。
     */
    public function DescribeInstancesStatus(Models\DescribeInstancesStatusRequest $request): Models\DescribeInstancesStatusResponse
    {
        return $this->call('DescribeInstancesStatus', $request, Models\DescribeInstancesStatusResponse::class);
    }

    /**
     * 启动一个或多个虚拟机实例。
     */
    public function StartInstances(Models\StartInstancesRequest $request): Models\StartInstancesResponse
    {
        return $this->call('StartInstances', $request, Models\StartInstancesResponse::class);
    }

    /**
     * 获取实例VNC地址。
     */
    public function DescribeVncUrl(Models\DescribeVncUrlRequest $request): Models\DescribeVncUrlResponse
    {
        return $this->call('DescribeVncUrl', $request, Models\DescribeVncUrlResponse::class);
    }

    /**
     * 修改虚拟机实例的属性（目前只支持修改实例的显示名称）。
     */
    public function ModifyInstancesAttribute(Models\ModifyInstancesAttributeRequest $request): Models\ModifyInstancesAttributeResponse
    {
        return $this->call('ModifyInstancesAttribute', $request, Models\ModifyInstancesAttributeResponse::class);
    }

    /**
     * 关闭一个或多个虚拟机实例。
     */
    public function StopInstances(Models\StopInstancesRequest $request): Models\StopInstancesResponse
    {
        return $this->call('StopInstances', $request, Models\StopInstancesResponse::class);
    }

    /**
     * 重启一个或多个虚拟机实例。
     */
    public function RebootInstances(Models\RebootInstancesRequest $request): Models\RebootInstancesResponse
    {
        return $this->call('RebootInstances', $request, Models\RebootInstancesResponse::class);
    }

    /**
     * 修改一台虚拟机实例的机型。
     */
    public function ModifyInstanceType(Models\ModifyInstanceTypeRequest $request): Models\ModifyInstanceTypeResponse
    {
        return $this->call('ModifyInstanceType', $request, Models\ModifyInstanceTypeResponse::class);
    }

    /**
     * 查询实例变配后的机型状态。
     */
    public function DescribeInstanceTypeStatus(Models\DescribeInstanceTypeStatusRequest $request): Models\DescribeInstanceTypeStatusResponse
    {
        return $this->call('DescribeInstanceTypeStatus', $request, Models\DescribeInstanceTypeStatusResponse::class);
    }

    /**
     * 虚拟机实例修改流量包询价。
     */
    public function InquiryPriceInstanceTrafficPackage(Models\InquiryPriceInstanceTrafficPackageRequest $request): Models\InquiryPriceInstanceTrafficPackageResponse
    {
        return $this->call('InquiryPriceInstanceTrafficPackage', $request, Models\InquiryPriceInstanceTrafficPackageResponse::class);
    }

    /**
     * 修改虚拟机实例流量包大小。
     */
    public function ModifyInstanceTrafficPackage(Models\ModifyInstanceTrafficPackageRequest $request): Models\ModifyInstanceTrafficPackageResponse
    {
        return $this->call('ModifyInstanceTrafficPackage', $request, Models\ModifyInstanceTrafficPackageResponse::class);
    }

    /**
     * 取消虚拟机实例流量包降配订单。
     */
    public function CancelInstanceTrafficPackageDowngrade(Models\CancelInstanceTrafficPackageDowngradeRequest $request): Models\CancelInstanceTrafficPackageDowngradeResponse
    {
        return $this->call('CancelInstanceTrafficPackageDowngrade', $request, Models\CancelInstanceTrafficPackageDowngradeResponse::class);
    }

    /**
     * 修改虚拟机实例的公网出口带宽。
     */
    public function ModifyInstanceBandwidth(Models\ModifyInstanceBandwidthRequest $request): Models\ModifyInstanceBandwidthResponse
    {
        return $this->call('ModifyInstanceBandwidth', $request, Models\ModifyInstanceBandwidthResponse::class);
    }

    /**
     * 取消虚拟机实例带宽降配订单。
     */
    public function CancelInstanceBandwidthDowngrade(Models\CancelInstanceBandwidthDowngradeRequest $request): Models\CancelInstanceBandwidthDowngradeResponse
    {
        return $this->call('CancelInstanceBandwidthDowngrade', $request, Models\CancelInstanceBandwidthDowngradeResponse::class);
    }

    /**
     * 查询实例带宽、流量包状态。
     */
    public function DescribeInstanceInternetStatus(Models\DescribeInstanceInternetStatusRequest $request): Models\DescribeInstanceInternetStatusResponse
    {
        return $this->call('DescribeInstanceInternetStatus', $request, Models\DescribeInstanceInternetStatusResponse::class);
    }

    /**
     * 取消虚拟机实例降配订单。
     */
    public function CancelInstanceDowngrade(Models\CancelInstanceDowngradeRequest $request): Models\CancelInstanceDowngradeResponse
    {
        return $this->call('CancelInstanceDowngrade', $request, Models\CancelInstanceDowngradeResponse::class);
    }

    /**
     * 退还一个虚拟机实例。
     */
    public function TerminateInstance(Models\TerminateInstanceRequest $request): Models\TerminateInstanceResponse
    {
        return $this->call('TerminateInstance', $request, Models\TerminateInstanceResponse::class);
    }

    /**
     * 释放一个或多个虚拟机实例。
     */
    public function ReleaseInstances(Models\ReleaseInstancesRequest $request): Models\ReleaseInstancesResponse
    {
        return $this->call('ReleaseInstances', $request, Models\ReleaseInstancesResponse::class);
    }

    /**
     * 虚拟机实例修改带宽询价。
     */
    public function InquiryPriceInstanceBandwidth(Models\InquiryPriceInstanceBandwidthRequest $request): Models\InquiryPriceInstanceBandwidthResponse
    {
        return $this->call('InquiryPriceInstanceBandwidth', $request, Models\InquiryPriceInstanceBandwidthResponse::class);
    }

    /**
     * 查询实例指定时间段内的流量信息。
     */
    public function DescribeInstanceTraffic(Models\DescribeInstanceTrafficRequest $request): Models\DescribeInstanceTrafficResponse
    {
        return $this->call('DescribeInstanceTraffic', $request, Models\DescribeInstanceTrafficResponse::class);
    }

    /**
     * 查询实例指定时间段内的CPU使用率。
     */
    public function DescribeInstanceCpuMonitor(Models\DescribeInstanceCpuMonitorRequest $request): Models\DescribeInstanceCpuMonitorResponse
    {
        return $this->call('DescribeInstanceCpuMonitor', $request, Models\DescribeInstanceCpuMonitorResponse::class);
    }

    /**
     * 查询云硬盘支持的类型。
     */
    public function DescribeDiskCategory(Models\DescribeDiskCategoryRequest $request): Models\DescribeDiskCategoryResponse
    {
        return $this->call('DescribeDiskCategory', $request, Models\DescribeDiskCategoryResponse::class);
    }

    /**
     * 创建云硬盘询价。
     */
    public function InquiryPriceCreateDisks(Models\InquiryPriceCreateDisksRequest $request): Models\InquiryPriceCreateDisksResponse
    {
        return $this->call('InquiryPriceCreateDisks', $request, Models\InquiryPriceCreateDisksResponse::class);
    }

    /**
     * 查询云硬盘列表。
     */
    public function DescribeDisks(Models\DescribeDisksRequest $request): Models\DescribeDisksResponse
    {
        return $this->call('DescribeDisks', $request, Models\DescribeDisksResponse::class);
    }

    /**
     * 创建一个或多个云硬盘。
     */
    public function CreateDisks(Models\CreateDisksRequest $request): Models\CreateDisksResponse
    {
        return $this->call('CreateDisks', $request, Models\CreateDisksResponse::class);
    }

    /**
     * 修改一个或多个云硬盘属性。
     */
    public function ModifyDisksAttributes(Models\ModifyDisksAttributesRequest $request): Models\ModifyDisksAttributesResponse
    {
        return $this->call('ModifyDisksAttributes', $request, Models\ModifyDisksAttributesResponse::class);
    }

    /**
     * 挂载云硬盘到云主机实例。
     */
    public function AttachDisks(Models\AttachDisksRequest $request): Models\AttachDisksResponse
    {
        return $this->call('AttachDisks', $request, Models\AttachDisksResponse::class);
    }

    /**
     * 从云主机实例上卸载云硬盘。
     */
    public function DetachDisks(Models\DetachDisksRequest $request): Models\DetachDisksResponse
    {
        return $this->call('DetachDisks', $request, Models\DetachDisksResponse::class);
    }

    /**
     * 将一个或多个已经挂载到一台实例的云硬盘挂载到另外一台实例上。
     */
    public function ChangeDisksAttach(Models\ChangeDisksAttachRequest $request): Models\ChangeDisksAttachResponse
    {
        return $this->call('ChangeDisksAttach', $request, Models\ChangeDisksAttachResponse::class);
    }

    /**
     * 终止云硬盘。
     */
    public function TerminateDisk(Models\TerminateDiskRequest $request): Models\TerminateDiskResponse
    {
        return $this->call('TerminateDisk', $request, Models\TerminateDiskResponse::class);
    }

    /**
     * 修改云硬盘所属的资源组。
     */
    public function ModifyDisksResourceGroup(Models\ModifyDisksResourceGroupRequest $request): Models\ModifyDisksResourceGroupResponse
    {
        return $this->call('ModifyDisksResourceGroup', $request, Models\ModifyDisksResourceGroupResponse::class);
    }

    /**
     * 将一个云硬盘扩容到指定大小。
     */
    public function ResizeDisk(Models\ResizeDiskRequest $request): Models\ResizeDiskResponse
    {
        return $this->call('ResizeDisk', $request, Models\ResizeDiskResponse::class);
    }

    /**
     * 释放云硬盘。
     */
    public function ReleaseDisk(Models\ReleaseDiskRequest $request): Models\ReleaseDiskResponse
    {
        return $this->call('ReleaseDisk', $request, Models\ReleaseDiskResponse::class);
    }

    /**
     * 续费云硬盘。
     */
    public function RenewDisk(Models\RenewDiskRequest $request): Models\RenewDiskResponse
    {
        return $this->call('RenewDisk', $request, Models\RenewDiskResponse::class);
    }

    /**
     * 查询可创建镜像的配额。
     */
    public function DescribeImageQuota(Models\DescribeImageQuotaRequest $request): Models\DescribeImageQuotaResponse
    {
        return $this->call('DescribeImageQuota', $request, Models\DescribeImageQuotaResponse::class);
    }

    /**
     * 查看镜像列表。
     */
    public function DescribeImages(Models\DescribeImagesRequest $request): Models\DescribeImagesResponse
    {
        return $this->call('DescribeImages', $request, Models\DescribeImagesResponse::class);
    }

    /**
     * 创建自定义镜像。
     */
    public function CreateImage(Models\CreateImageRequest $request): Models\CreateImageResponse
    {
        return $this->call('CreateImage', $request, Models\CreateImageResponse::class);
    }

    /**
     * 修改镜像属性。
     */
    public function ModifyImagesAttributes(Models\ModifyImagesAttributesRequest $request): Models\ModifyImagesAttributesResponse
    {
        return $this->call('ModifyImagesAttributes', $request, Models\ModifyImagesAttributesResponse::class);
    }

    /**
     * 删除一个或多个镜像。
     */
    public function DeleteImages(Models\DeleteImagesRequest $request): Models\DeleteImagesResponse
    {
        return $this->call('DeleteImages', $request, Models\DeleteImagesResponse::class);
    }

    /**
     * 查询一台或多台指定子网的信息。用户可以根据Subnet ID、区域、Subnet名称等信息来搜索Subnet信息。
     */
    public function DescribeSubnets(Models\DescribeSubnetsRequest $request): Models\DescribeSubnetsResponse
    {
        return $this->call('DescribeSubnets', $request, Models\DescribeSubnetsResponse::class);
    }

    /**
     * 创建子网。
     */
    public function CreateSubnet(Models\CreateSubnetRequest $request): Models\CreateSubnetResponse
    {
        return $this->call('CreateSubnet', $request, Models\CreateSubnetResponse::class);
    }

    /**
     * 修改子网的属性（目前只支持修改子网的名称）。
     */
    public function ModifySubnetsAttribute(Models\ModifySubnetsAttributeRequest $request): Models\ModifySubnetsAttributeResponse
    {
        return $this->call('ModifySubnetsAttribute', $request, Models\ModifySubnetsAttributeResponse::class);
    }

    /**
     * 删除一个子网。
     */
    public function DeleteSubnet(Models\DeleteSubnetRequest $request): Models\DeleteSubnetResponse
    {
        return $this->call('DeleteSubnet', $request, Models\DeleteSubnetResponse::class);
    }

    /**
     * 查询一个或多个指定安全组的信息。用户可以根据安全组ID、安全组名称等信息来搜索安全组信息。
     */
    public function DescribeSecurityGroups(Models\DescribeSecurityGroupsRequest $request): Models\DescribeSecurityGroupsResponse
    {
        return $this->call('DescribeSecurityGroups', $request, Models\DescribeSecurityGroupsResponse::class);
    }

    /**
     * 创建安全组。
     */
    public function CreateSecurityGroup(Models\CreateSecurityGroupRequest $request): Models\CreateSecurityGroupResponse
    {
        return $this->call('CreateSecurityGroup', $request, Models\CreateSecurityGroupResponse::class);
    }

    /**
     * 修改安全组的属性（目前只支持修改安全组的名称）。
     */
    public function ModifySecurityGroupsAttribute(Models\ModifySecurityGroupsAttributeRequest $request): Models\ModifySecurityGroupsAttributeResponse
    {
        return $this->call('ModifySecurityGroupsAttribute', $request, Models\ModifySecurityGroupsAttributeResponse::class);
    }

    /**
     * 删除安全组。
     */
    public function DeleteSecurityGroup(Models\DeleteSecurityGroupRequest $request): Models\DeleteSecurityGroupResponse
    {
        return $this->call('DeleteSecurityGroup', $request, Models\DeleteSecurityGroupResponse::class);
    }

    /**
     * 配置安全组的规则。
     */
    public function ConfigureSecurityGroupRules(Models\ConfigureSecurityGroupRulesRequest $request): Models\ConfigureSecurityGroupRulesResponse
    {
        return $this->call('ConfigureSecurityGroupRules', $request, Models\ConfigureSecurityGroupRulesResponse::class);
    }

    /**
     * 移除安全组的规则。
     */
    public function RevokeSecurityGroupRules(Models\RevokeSecurityGroupRulesRequest $request): Models\RevokeSecurityGroupRulesResponse
    {
        return $this->call('RevokeSecurityGroupRules', $request, Models\RevokeSecurityGroupRulesResponse::class);
    }

    /**
     * 为安全组绑定实例。
     */
    public function AssociateSecurityGroupInstance(Models\AssociateSecurityGroupInstanceRequest $request): Models\AssociateSecurityGroupInstanceResponse
    {
        return $this->call('AssociateSecurityGroupInstance', $request, Models\AssociateSecurityGroupInstanceResponse::class);
    }

    /**
     * 为安全组解绑实例。
     */
    public function UnAssociateSecurityGroupInstance(Models\UnAssociateSecurityGroupInstanceRequest $request): Models\UnAssociateSecurityGroupInstanceResponse
    {
        return $this->call('UnAssociateSecurityGroupInstance', $request, Models\UnAssociateSecurityGroupInstanceResponse::class);
    }

    /**
     * 获取实例可绑定的安全组。
     */
    public function DescribeInstanceAvailableSecurityGroupResources(Models\DescribeInstanceAvailableSecurityGroupResourcesRequest $request): Models\DescribeInstanceAvailableSecurityGroupResourcesResponse
    {
        return $this->call('DescribeInstanceAvailableSecurityGroupResources', $request, Models\DescribeInstanceAvailableSecurityGroupResourcesResponse::class);
    }

    /**
     * 新增安全组的规则。
     */
    public function AuthorizeSecurityGroupRules(Models\AuthorizeSecurityGroupRulesRequest $request): Models\AuthorizeSecurityGroupRulesResponse
    {
        return $this->call('AuthorizeSecurityGroupRules', $request, Models\AuthorizeSecurityGroupRulesResponse::class);
    }

    /**
     * 新增安全组单条规则。
     */
    public function AuthorizeSecurityGroupRule(Models\AuthorizeSecurityGroupRuleRequest $request): Models\AuthorizeSecurityGroupRuleResponse
    {
        return $this->call('AuthorizeSecurityGroupRule', $request, Models\AuthorizeSecurityGroupRuleResponse::class);
    }
}
