<?php

/*
 * SPDX-License-Identifier: Apache-2.0
 * Derived from the official Zenlayer Cloud SDK schema and modified for
 * PHP/Laravel. See NOTICE and UPSTREAM.md for attribution and revisions.
 */

declare(strict_types=1);

namespace ZenlayerCloud\Laravel\Ipt\V20240901;

use ZenlayerCloud\Laravel\Common\AbstractClient;

/**
 * Zenlayer Cloud IP Transit (IPT) client (API version 2024-09-01).
 *
 * Each public method maps 1:1 to an official Action name. The public API
 * reference is at https://docs.console.zenlayer.com/api-reference/cn/networking/ipt;
 * UPSTREAM.md records any Action currently present only in the official SDKs.
 * Method names remain PascalCase so the protocol mapping is unambiguous.
 *
 * @generated by bin/codegen.php — do not edit by hand.
 */
class IptClient extends AbstractClient
{
    protected function service(): string
    {
        return 'ipt';
    }

    protected function apiVersion(): string
    {
        return '2024-09-01';
    }

    /**
     * 查询IP Transit可连接数据中心
     */
    public function DescribeIPTransitDatacenters(#[\SensitiveParameter] Models\DescribeIPTransitDatacentersRequest $request): Models\DescribeIPTransitDatacentersResponse
    {
        return $this->call('DescribeIPTransitDatacenters', $request, Models\DescribeIPTransitDatacentersResponse::class);
    }

    /**
     * 查询IP Transit可用 ASN
     */
    public function DescribeIPTransitAvailableAsns(#[\SensitiveParameter] Models\DescribeIPTransitAvailableAsnsRequest $request): Models\DescribeIPTransitAvailableAsnsResponse
    {
        return $this->call('DescribeIPTransitAvailableAsns', $request, Models\DescribeIPTransitAvailableAsnsResponse::class);
    }

    /**
     * 查询IP Transit可用公网地址段
     */
    public function DescribeIPTransitAvailableCidrBlocks(#[\SensitiveParameter] Models\DescribeIPTransitAvailableCidrBlocksRequest $request): Models\DescribeIPTransitAvailableCidrBlocksResponse
    {
        return $this->call('DescribeIPTransitAvailableCidrBlocks', $request, Models\DescribeIPTransitAvailableCidrBlocksResponse::class);
    }

    /**
     * iP Transit创建询价
     */
    public function InquiryCreateIPTransitPrice(#[\SensitiveParameter] Models\InquiryCreateIPTransitPriceRequest $request): Models\InquiryCreateIPTransitPriceResponse
    {
        return $this->call('InquiryCreateIPTransitPrice', $request, Models\InquiryCreateIPTransitPriceResponse::class);
    }

    /**
     * 创建IP Transit
     */
    public function CreateIPTransit(#[\SensitiveParameter] Models\CreateIPTransitRequest $request): Models\CreateIPTransitResponse
    {
        return $this->call('CreateIPTransit', $request, Models\CreateIPTransitResponse::class);
    }

    /**
     * 查询IP Transit列表
     */
    public function DescribeIPTransits(#[\SensitiveParameter] Models\DescribeIPTransitsRequest $request): Models\DescribeIPTransitsResponse
    {
        return $this->call('DescribeIPTransits', $request, Models\DescribeIPTransitsResponse::class);
    }

    /**
     * 修改IP Transit带宽
     */
    public function ModifyIPTransitBandwidth(#[\SensitiveParameter] Models\ModifyIPTransitBandwidthRequest $request): Models\ModifyIPTransitBandwidthResponse
    {
        return $this->call('ModifyIPTransitBandwidth', $request, Models\ModifyIPTransitBandwidthResponse::class);
    }

    /**
     * 修改IP Transit属性
     */
    public function ModifyIPTransitsAttribute(#[\SensitiveParameter] Models\ModifyIPTransitsAttributeRequest $request): Models\ModifyIPTransitsAttributeResponse
    {
        return $this->call('ModifyIPTransitsAttribute', $request, Models\ModifyIPTransitsAttributeResponse::class);
    }

    /**
     * 删除IP Transit
     */
    public function DeleteIPTransit(#[\SensitiveParameter] Models\DeleteIPTransitRequest $request): Models\DeleteIPTransitResponse
    {
        return $this->call('DeleteIPTransit', $request, Models\DeleteIPTransitResponse::class);
    }

    /**
     * 查询IP Transit流量
     */
    public function DescribeIPTransitTraffic(#[\SensitiveParameter] Models\DescribeIPTransitTrafficRequest $request): Models\DescribeIPTransitTrafficResponse
    {
        return $this->call('DescribeIPTransitTraffic', $request, Models\DescribeIPTransitTrafficResponse::class);
    }

    /**
     * IP Transit变配询价
     */
    public function InquiryModifyIPTransitPrice(#[\SensitiveParameter] Models\InquiryModifyIPTransitPriceRequest $request): Models\InquiryModifyIPTransitPriceResponse
    {
        return $this->call('InquiryModifyIPTransitPrice', $request, Models\InquiryModifyIPTransitPriceResponse::class);
    }

    /**
     * 修改IP Transit配置
     */
    public function ModifyIPTransitConfig(#[\SensitiveParameter] Models\ModifyIPTransitConfigRequest $request): Models\ModifyIPTransitConfigResponse
    {
        return $this->call('ModifyIPTransitConfig', $request, Models\ModifyIPTransitConfigResponse::class);
    }
}
